// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.CharacterEditor.Editors.Species.Controls;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Editors.Species;

[GenerateTypedNameReferences]
public sealed partial class SpeciesSelectorPanel : CharacterEditorPanel
{
    public override CharacterEditorPanelLayout Layout => CharacterEditorPanelLayout.Side;

    public SpeciesSelectorPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}