// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Shared._Starlight.CharacterProfiles;
using Content.Shared._Starlight.CharacterProfiles.Data;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.CharacterEditor.Editors.Species;

[GenerateTypedNameReferences]
public sealed partial class SpeciesSelectorPanel : CharacterEditorPanel
{

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private string _localizedSpeciesName = string.Empty;

    public SpeciesSelectorPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SetupEditorFields();
        LowerSection.Margin = new Thickness(5);
        CustomSpeciesBox.SeparationOverride = 5;
    }

    private void SetupEditorFields()
    {
    }

    private string GetCustomSpeciesField(CharacterSpeciesData data)
    {
        _localizedSpeciesName = Loc.GetString(_prototypeManager.Index(data.BaseSpecies).Name);
        return data.CustomSpeciesName == string.Empty ? _localizedSpeciesName : data.CustomSpeciesName;
    }

    private void SetCustomSpeciesField(string name, CharacterProfile profile, CharacterSpeciesData data)
    {
        if (name != _localizedSpeciesName) data.CustomSpeciesName = name;
    }
};