// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Editors.Species;

[GenerateTypedNameReferences]
public sealed partial class SpeciesSelector : EditorModeWidget
{
    public SpeciesSelector()
    {
        RobustXamlLoader.Load(this);
    }
}