// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Screens;

[GenerateTypedNameReferences]
public sealed partial class SLCharacterEditorLayer : UIScreenLayer
{
    public SLCharacterEditorLayer()
    {
        RobustXamlLoader.Load(this);
        SetAnchorPreset(BackgroundPanel, LayoutPreset.Wide, true);
    }

    protected override void AddedToScreen()
    {
        if (ParentScreen == null || !ParentScreen.TryGetLayer<SLLobbyLayer>(out var lobbyLayer, true))
        {
            Log.Error($"Character Editor could not find LobbyLayer to hide!");
            return;
        }
        lobbyLayer.Visible = false;
    }

    protected override void RemovedFromScreen()
    {
        if (ParentScreen == null || !ParentScreen.TryGetLayer<SLLobbyLayer>(out var lobbyLayer, true))
        {
            Log.Error($"Character Editor could not find LobbyLayer to hide!");
            return;
        }
        lobbyLayer.Visible = true;
    }
}