// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Screens;

[GenerateTypedNameReferences]
public sealed partial class SLLobbyScreen : UIScreen
{
    public SLLobbyScreen()
    {
        RobustXamlLoader.Load(this);
        RegisterLayer<SLLobbyLayer>();
        RegisterLayer<SLCharacterEditorLayer>();
    }
}