// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.GameTicking.Managers;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Screens;

[GenerateTypedNameReferences]
public sealed partial class SLLobbyLayer : UIScreenLayer
{
    private ClientGameTicker _gameTicker = default!;

    public override bool HideLayersBelow => false; //TODO: Jezi testing
    public override bool HideParentScreen => true; //TODO: Jezi testing
    public SLLobbyLayer()
    {
        RobustXamlLoader.Load(this);

        _gameTicker = EntityManager.System<ClientGameTicker>();

        _gameTicker.LobbyStatusUpdated += LobbyStatusUpdated;
        SetAnchorPreset(MainContainer, LayoutPreset.Wide);
        RightSide.SetWidth = Cfg.GetCVar(CCVars.ServerLobbyRightPanelWidth);

        LobbyStatusUpdated();
    }
    private void LobbyStatusUpdated()
    {

    }
}