// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.GameTicking.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Layers;

[GenerateTypedNameReferences]
public sealed partial class SLLobbyScreenTest : UIScreenLayer
{
    [Dependency] private IResourceCache _resourceCache = default!;

    private ClientGameTicker _gameTicker = default!;
    public SLLobbyScreenTest()
    {
        RobustXamlLoader.Load(this);
        SetAnchorPreset(Background, LayoutPreset.Wide);
        _gameTicker = EntityManager.System<ClientGameTicker>();
        _gameTicker.LobbyStatusUpdated += LobbyStatusUpdated;
        LobbyStatusUpdated();
    }

    private void LobbyStatusUpdated()
    {
        if (_gameTicker.LobbyBackground != null)
        {
            Background.Texture = _resourceCache.GetResource<TextureResource>(_gameTicker.LobbyBackground);
        }
        else
        {
            Background.Texture = null;
        }
    }
}