// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.GameTicking.Managers;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Layers;

[GenerateTypedNameReferences]
public sealed partial class SLLobbyLayer : UIScreenLayer
{
    private ClientGameTicker _gameTicker = default!;
    public SLLobbyLayer()
    {
        RobustXamlLoader.Load(this);

        _gameTicker = EntityManager.System<ClientGameTicker>();
        SetAnchorPreset(MainContainer, LayoutPreset.Wide);
        SidePanel.SetWidth = Cfg.GetCVar(CCVars.ServerLobbyRightPanelWidth);

        LobbyStatusUpdated();

        CollapseButton.OnPressed += CollapseSideBar;
        ExpandButton.OnPressed += ExpandSideBar;
    }

    protected override void AddedToScreen()
    {
        _gameTicker.LobbyStatusUpdated += LobbyStatusUpdated;
    }

    protected override void RemovedFromScreen()
    {
        _gameTicker.LobbyStatusUpdated -= LobbyStatusUpdated;
    }

    private void ExpandSideBar(BaseButton.ButtonEventArgs obj)
    {
        if (SidePanel.Visible)
            return;
        SidePanel.Visible = true;
        ExpandPanel.Visible = false;
    }

    private void CollapseSideBar(BaseButton.ButtonEventArgs obj)
    {
        if (!SidePanel.Visible)
            return;
        SidePanel.Visible = false;
        ExpandPanel.Visible = true;
    }

    private void LobbyStatusUpdated()
    {

    }
}