// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.UI;
using Content.Shared._Starlight.CharacterProfiles.Data;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.CharacterEditor.Editors.Species.Controls;

[GenerateTypedNameReferences]
public sealed partial class SpeciesGroupList : SLBox
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public string? GroupName { get => SpeciesGroupLabel.Text; set => SpeciesGroupLabel.Text = value; }
    public int Columns { get => SpeciesGrid.Columns; set => SpeciesGrid.Columns = value; }

    private Dictionary<ProtoId<SpeciesPrototype>, SpeciesSelectorButton> _speciesSelectors = new();

    private ButtonGroup _speciesButtonGroup = new (false);

    private SpriteSystem? _spriteSystem = null;
    private bool _populated = false;
    public SpeciesGroupList()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void EnteredTree()
    {
        SubscribeUIEvent<CharacterEditorProfileDirtiedUIEvent>(OnCharacterDirtied);
        _prototypeManager.PrototypesReloaded += OnProtoReloaded;
        EnsureSpeciesList();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _prototypeManager.PrototypesReloaded -= OnProtoReloaded;
        ClearSpecies();
    }

    private void OnProtoReloaded(PrototypesReloadedEventArgs args)
    {
        if (!args.WasModified<SpeciesPrototype>())
            return;
        ClearSpecies();
        PopulateSpecies();
    }

    private void OnCharacterDirtied(ref readonly CharacterEditorProfileDirtiedUIEvent args)
    {
        EnsureSpeciesList(); //we have to do a differed init because UIScreen lifecycle bs
        SelectSpeciesButton(args.Profile.GetData<CharacterSpeciesData>().BaseSpecies);
    }
    public void SelectSpeciesButton(ProtoId<SpeciesPrototype> species)
    {
        if (_speciesSelectors.TryGetValue(species, out var button))
            button.SetClickPressed(true);
    }

    public SpeciesSelectorButton GetButtonForSpecies(ProtoId<SpeciesPrototype> species)
    {
        return _speciesSelectors[species];
    }

    public void AddSpecies(ProtoId<SpeciesPrototype> species, Texture icon, string localizedName)
    {
        var newSpeciesSelector = new SpeciesSelectorButton(species, icon, localizedName, _speciesButtonGroup);
        SpeciesGrid.AddChild(newSpeciesSelector);
        _speciesSelectors.Add(species, newSpeciesSelector);
    }

    public void ClearSpecies()
    {
        SpeciesGrid.RemoveAllChildren();
        _populated = false;
    }

    private void EnsureSpeciesList()
    {
        if (_populated)
            return;
        PopulateSpecies();
    }

    private void PopulateSpecies()
    {
        _spriteSystem ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        if (_populated)
            return;
        foreach (var species in _prototypeManager.EnumeratePrototypes<SpeciesPrototype>())
        {
            if (!species.RoundStart)
                continue;
            AddSpecies(species, _spriteSystem.Frame0(species.SpeciesIcon), Loc.GetString(species.Name));
        }
        _populated = true;
    }
}