// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.UIEvents;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.CharacterEditor.Editors.Species.Controls;

[GenerateTypedNameReferences]
public sealed partial class SpeciesSelectorButton : ContainerButton, IUIEventSubscriber
{
    public ProtoId<SpeciesPrototype> Species { get; set; }
    public SpeciesSelectorButton()
    {
        RobustXamlLoader.Load(this);
        AddStyleClass(StyleClassButton);
        OnToggled += OnSelected;
    }

    private void OnSelected(ButtonToggledEventArgs args)
    {
        Disabled = true;
        UserInterfaceManager.RaiseUIEvent(this,new SelectedUIEvent(Species));
    }

    public SpeciesSelectorButton(ProtoId<SpeciesPrototype> newSpecies, Texture newIcon, string localizedName) : this()
    {
        SetData(newSpecies, newIcon, localizedName);
    }

    public void Select()
    {
        if (Pressed)
            return;
        Pressed = true;
        Disabled = true;
        UserInterfaceManager.RaiseUIEvent(this,new SelectedUIEvent(Species));
    }

    public void Deselect()
    {
        if (!Pressed)
            return;
        Pressed = false;
        Disabled = false;
    }

    public void SetData(ProtoId<SpeciesPrototype> newSpecies, Texture newIcon, string localizedName)
    {
        SpeciesIcon.Texture = newIcon;
        SpeciesLabel.Text = localizedName;
        Species = newSpecies;
    }

    public record struct SelectedUIEvent(ProtoId<SpeciesPrototype> Species);
}