// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.UIEvents;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.CharacterEditor.Editors.Species.Controls;

[GenerateTypedNameReferences]
public sealed partial class SpeciesSelectorButton : ContainerButton, IUIEventSubscriber
{
    public ProtoId<SpeciesPrototype> Species { get; set; }
    public SpeciesSelectorButton()
    {
        RobustXamlLoader.Load(this);
        AddStyleClass(StyleClassButton);
    }

    public SpeciesSelectorButton(ProtoId<SpeciesPrototype> newSpecies, Texture newIcon, string localizedName, ButtonGroup buttonGroup) : this()
    {
        Group = buttonGroup;
        SetData(newSpecies, newIcon, localizedName);
    }
    public void SetData(ProtoId<SpeciesPrototype> newSpecies, Texture newIcon, string localizedName)
    {
        SpeciesIcon.Texture = newIcon;
        SpeciesLabel.Text = localizedName;
        Species = newSpecies;
    }
}