// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.CharacterEditor.Editors.Species.Controls;

[GenerateTypedNameReferences]
public sealed partial class SpeciesGroupList : BoxContainer
{
    public string? GroupName { get => SpeciesGroupLabel.Text; set => SpeciesGroupLabel.Text = value; }
    public int Columns { get => SpeciesGrid.Columns; set => SpeciesGrid.Columns = value; }

    private Dictionary<ProtoId<SpeciesPrototype>, SpeciesSelectorButton> _speciesSelectors = new();

    private ButtonGroup _speciesButtonGroup = new (false);
    public SpeciesGroupList()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public SpeciesSelectorButton GetButtonForSpecies(ProtoId<SpeciesPrototype> species)
    {
        return _speciesSelectors[species];
    }

    public void AddSpecies(ProtoId<SpeciesPrototype> species, Texture icon, string localizedName)
    {
        var newSpeciesSelector = new SpeciesSelectorButton(species, icon, localizedName, _speciesButtonGroup);
        SpeciesGrid.AddChild(newSpeciesSelector);
        _speciesSelectors.Add(species, newSpeciesSelector);
    }

    public void ClearSpecies()
    {
        SpeciesGrid.RemoveAllChildren();
    }
}