// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Editors.BodyType;

[GenerateTypedNameReferences]
public sealed partial class BodyTypePanel : CharacterEditorPanel
{
    public override CharacterEditorPanelLayout Layout => CharacterEditorPanelLayout.Main;

    public BodyTypePanel()
    {
        RobustXamlLoader.Load(this);
    }

}