// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Shared._Starlight.CharacterProfiles.Data;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;

namespace Content.Client._Starlight.CharacterEditor.Editors.BodyType;

[GenerateTypedNameReferences]
public sealed partial class IdentityPanel : CharacterEditorPanel
{
    private const int MinAge = 18;
    public override CharacterEditorPanelLayout Layout => CharacterEditorPanelLayout.Main;

    public IdentityPanel()
    {
        RobustXamlLoader.Load(this);
        Margin = new Thickness(10);

        SetupEditorFields();

        NameRuleDisclaimer.Text =
            "Warning: Offensive or LRP IC names will lead\n to admin intervention on this server. \n Read our [Rules] for more.";
        NameRuleDisclaimer.FontColorOverride = Color.Red;
    }
    private void SetupEditorFields()
    {
        CharacterBodyTypeField.InitializeAsEnumField((Sex bodyType, ref CharacterIdentityData data) =>
        {
            data.BodyType = bodyType;
        }, data => data.BodyType);

        CharacterPronounField.InitializeAsEnumField((Gender gender, ref CharacterIdentityData data) =>
        {
            data.Gender = gender;
        }, data => data.Gender);

        FirstNameField.InitializeAsTextField( (string name, ref CharacterIdentityData data) => { data.Name = name; },
            data => data.Name);

        NicknameField.InitializeAsTextField( (string name, ref CharacterIdentityData data) => { data.Nickname = name;},
            data => data.Nickname);

        LastNameField.InitializeAsTextField((string name, ref CharacterIdentityData data) => { data.LastName = name; },
            data => data.LastName);

        CharacterPhysicalAgeField.InitializeAsTextField((string ageIn, ref CharacterIdentityData data) =>
        {
            if (int.TryParse(ageIn, out var age))
            {
                data.PhysicalAge = int.Max(age, MinAge);
                return;
            }
            CharacterPhysicalAgeField.SetTextFieldValue(data.PhysicalAge.ToString());
        }, data => data.PhysicalAge.ToString());

        CharacterChronologicalAgeField.InitializeAsTextField((string ageIn, ref CharacterIdentityData data) =>
        {
            if (int.TryParse(ageIn, out var age))
            {
                data.ChronologicalAge = int.Max(age, MinAge);
                return;
            }
            CharacterChronologicalAgeField.SetTextFieldValue(data.ChronologicalAge.ToString());
        }, data => data.ChronologicalAge.ToString());
    }
}