// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.UI.Core;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public sealed partial class EditCharacterButton : Button
{
    public EditCharacterButton()
    {
        RobustXamlLoader.Load(this);
        OnPressed += HandlePressed;
    }

    private void HandlePressed(ButtonEventArgs obj)
    {
        UIEvents.RaiseEvent(new EnterCharacterEditorUIEvent());
    }
}