// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.UserInterface.Systems.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public sealed partial class GuidebookButton : Button
{
    [Dependency] private readonly IUserInterfaceManager _UI = default!;
    public GuidebookButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var guideController = _UI.GetUIController<GuidebookUIController>();
        OnPressed += _ =>
        {
            guideController.ToggleGuidebook();
        };
    }
}