// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public sealed partial class LobbyLeaveButton : Button
{
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly ITimerManager _timerMan = default!;

    private bool _showConfirmation = false;
    private const int ConfirmationDelay = 300;

    public string? ConfirmText { get => ConfirmLabel.Text; set => ConfirmLabel.Text = value; }


    public LobbyLeaveButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        OnPressed += HandlePressed;
    }

    private void ToggleConfirm(bool confirm)
    {
        if (_showConfirmation == confirm)
            return;
        ConfirmLabel.Visible = confirm;
        Label.Visible = !confirm;
        if (confirm)
        {
            AddStyleClass(StyleNano.ButtonCaution);
            Disabled = true;
            _timerMan.AddTimer(new Timer(ConfirmationDelay, false, () => Disabled = false));
        }
        else
        {
            RemoveStyleClass(StyleNano.ButtonCaution);
        }
        _showConfirmation = confirm;
    }

    private void HandlePressed(ButtonEventArgs obj)
    {
        if (!_showConfirmation)
        {
            ToggleConfirm(true);
            return;
        }
        ToggleConfirm(false);
        _console.ExecuteCommand("disconnect");
    }

    protected override void MouseExited()
    {
        if (_showConfirmation)
        {
            ToggleConfirm(false);
        }
    }

}