// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public abstract partial class LobbyWindow : DefaultWindow
{
    public virtual string? LobbyButtonText { get; } = null;

    public LobbyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}