// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0
// Modified from a file licensed under MIT (Space Wizards Federation)

using Content.Client._Starlight.UI;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public sealed partial class ReadyButton : SLBox
{
    [Dependency] private readonly IClientPreferencesManager _preferences = default!;

    private LateJoinGui? _lateJoinWindow = null;

    public ReadyButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Ready.TooltipSupplier = GetReadyButtonTooltip;
        LateJoinButton.TooltipSupplier = GetLateJoinButtonTooltip;
    }

    public void Refresh(bool gameStarted, bool cannotLateJoin)
    {
        if (gameStarted)
        {
            Ready.Pressed = false;
            Ready.Disabled = false;
            Ready.Visible = false;

            LateJoinButton.Visible = true;
            LateJoinButton.Disabled = false;
            if (LateJoinButton.SuppliedTooltip is Tooltip tooltip)
            {
                tooltip.Text = LateJoinButtonTooltipText();
            }
            Observe.Disabled = false;
            LateJoinButton.Disabled = cannotLateJoin;
        }
        else
        {
            Ready.Disabled = false;
            Ready.Visible = true;

            Observe.Disabled = true;
            LateJoinButton.Disabled = true;
            LateJoinButton.Visible = false;
            Ready.Text = Loc.GetString(Ready.Pressed ? "lobby-state-player-status-ready": "lobby-state-player-status-not-ready");
            // If there is a tooltip showing, make sure to update the text in it as well!
            if (Ready.SuppliedTooltip is Tooltip tooltip)
            {
                tooltip.Text = ReadyButtonTooltipText();
            }
        }
        // if (_gameTicker.ServerInfoBlob != null)
        // {
        //     Lobby!.ServerInfo.SetInfoBlob(_gameTicker.ServerInfoBlob);
        // }

        //Seriously?
        // var minutesToday = _playtimeTracking.PlaytimeMinutesToday;
        // if (minutesToday > 60)
        // {
        //     Lobby!.PlaytimeComment.Visible = true;
        //
        //     var hoursToday = Math.Round(minutesToday / 60f, 1);
        //
        //     var chosenString = minutesToday switch
        //     {
        //         < 180 => "lobby-state-playtime-comment-normal",
        //         < 360 => "lobby-state-playtime-comment-concerning",
        //         < 720 => "lobby-state-playtime-comment-grasstouchless",
        //         _ => "lobby-state-playtime-comment-selfdestructive"
        //     };
        //
        //     //Lobby.PlaytimeComment.SetMarkup(Loc.GetString(chosenString, ("hours", hoursToday)));
        // }
        // else
        //     //Lobby!.PlaytimeComment.Visible = false;
    }

    private string ReadyButtonTooltipText()
    {
        if (!_preferences.ServerDataLoaded)
            return Loc.GetString("ui-lobby-ready-button-tooltip-not-loaded");
        if ((_preferences.Preferences?.JobPrioritiesFiltered().Count ?? 0) == 0)
            return Loc.GetString("ui-lobby-ready-button-tooltip-no-possible-characters");
        if (Ready.Pressed)
            return Loc.GetString("ui-lobby-ready-button-tooltip-is-ready");
        return Loc.GetString("ui-lobby-ready-button-tooltip-is-not-ready");
    }

    private string LateJoinButtonTooltipText()
    {
        if (!_preferences.ServerDataLoaded)
            return Loc.GetString("ui-lobby-ready-button-tooltip-not-loaded");
        if ((_preferences.Preferences?.JobPrioritiesFiltered().Count ?? 0) == 0)
            return Loc.GetString("ui-lobby-ready-button-tooltip-no-possible-characters");
        return Loc.GetString("ui-lobby-ready-button-tooltip-join-state");
    }

    private Control GetReadyButtonTooltip(Control sender)
    {
        return new Tooltip { Text = ReadyButtonTooltipText() };
    }

    private Control GetLateJoinButtonTooltip(Control sender)
    {
        return new Tooltip { Text = LateJoinButtonTooltipText() };
    }
}