// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public sealed partial class RoundTimerControl : SLBox
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;


    public TimeSpan RoundStartTimeSpan;
    public TimeSpan RoundStartTime;
    public bool IsStarted = false;
    public bool IsPaused = false;

    public RoundTimerControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Refresh()
    {
        if (IsStarted)
        {
            StartTime.Text = string.Empty;
            var roundTime = _gameTiming.CurTime.Subtract(RoundStartTime);
            StartTime.Text = string.Empty;
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }
        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");

        string text;

        if (IsPaused)
        {
            text = Loc.GetString("lobby-state-paused");
        }
        else if (RoundStartTime < _gameTiming.CurTime)
        {
            StartTime.Text = Loc.GetString("lobby-state-soon");
            return;
        }
        else
        {
            var difference = RoundStartTime - _gameTiming.CurTime;
            var seconds = difference.TotalSeconds;
            if (seconds < 0)
            {
                text = Loc.GetString(seconds < -5 ? "lobby-state-right-now-question" : "lobby-state-right-now-confirmation");
            }
            else if (difference.TotalHours >= 1)
            {
                text = $"{Math.Floor(difference.TotalHours)}:{difference.Minutes:D2}:{difference.Seconds:D2}";
            }
            else
            {
                text = $"{difference.Minutes}:{difference.Seconds:D2}";
            }
        }
        StartTime.Text = Loc.GetString("lobby-state-round-start-countdown-text", ("timeLeft", text));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        Refresh();
    }
}