// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.Info;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public sealed partial class RulesButton : Button
{
    public RulesButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        OnPressed += _ => new RulesAndInfoWindow().Open();
    }
}