// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Controls;

public enum UILayerButtonMode
{
    ActivateLayer,
    DeactivateLayer,
    Toggle
}

[GenerateTypedNameReferences]
public sealed partial class UILayerButton : Button
{
    public Type? LayerType { get; set; } = null;
    public UILayerButtonMode OperationMode { get; set; } = UILayerButtonMode.ActivateLayer;

    public UILayerButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        OnPressed += HandlePressed;
    }

    private void HandlePressed(ButtonEventArgs obj)
    {
        if (LayerType == null || UserInterfaceManager.ActiveScreen == null)
            return;
        switch (OperationMode)
        {
            case UILayerButtonMode.ActivateLayer:
                {
                    UserInterfaceManager.ActiveScreen.EnableLayer(LayerType);
                    return;
                }
            case UILayerButtonMode.DeactivateLayer:
                {
                    UserInterfaceManager.ActiveScreen.DisableLayer(LayerType);
                    return;
                }
            case UILayerButtonMode.Toggle:
                {
                    if (UserInterfaceManager.ActiveScreen.HasLayer(LayerType, true))
                    {
                        UserInterfaceManager.ActiveScreen.DisableLayer(LayerType);
                        return;
                    }

                    UserInterfaceManager.ActiveScreen.EnableLayer(LayerType);
                    return;
                }
        }
    }
}