// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public sealed partial class URIButton : Button
{
    [Dependency] private readonly IUriOpener _uriOpener = default!;

    private bool _visibleWithoutURI = true;

    public bool VisibleWithoutURI
    {
        get => _visibleWithoutURI;
        set
        {
            if (value == _visibleWithoutURI)
                return;
            if (VisibleWithoutURI)
                Visible = true;
            Visible = !VisibleWithoutURI && _uri != null;
        }
    }

    private string? _uri = null;

    public string? URI
    {
        get => _uri;
        set
        {
            if (value == _uri)
                return;
            if (!VisibleWithoutURI)
                Visible = _uri != null;
        }
    }

    public URIButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        OnPressed += HandlePressed;
        Visible = VisibleWithoutURI;
    }

    private void HandlePressed(ButtonEventArgs obj)
    {
        if (URI == null)
            return;
        _uriOpener.OpenUri(URI);
    }
}