// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Controls;

[GenerateTypedNameReferences]
public sealed partial class WindowButton : Button
{
    [Dependency] private readonly IDynamicTypeFactory _typeFact = default!;
    public Type? WindowType { get; set; }
    public bool SingletonWindow { get; set; } = true;
    private BaseWindow? _window;

    private void Execute(ButtonEventArgs obj)
    {
        if (WindowType == null)
            return;
        if (!SingletonWindow || _window == null)
            _window = (BaseWindow) _typeFact.CreateInstance(WindowType);
        _window?.OpenCentered();
    }
    public WindowButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        OnPressed += Execute;
    }
}