// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Editors.BodyTypeEditor;

[GenerateTypedNameReferences]
public sealed partial class BodyTypeEditor : EditorModeWidget
{
    public BodyTypeEditor()
    {
        RobustXamlLoader.Load(this);
    }
}