// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client.GameTicking.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby;

[GenerateTypedNameReferences]
public sealed partial class SLDummyLobbyControl : Control
{
    public SLDummyLobbyControl()
    {
        RobustXamlLoader.Load(this);
        LayoutContainer.SetAnchorPreset(Background, LayoutContainer.LayoutPreset.Wide);
    }
}