// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor;
using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby;

[GenerateTypedNameReferences]
public sealed partial class SLDummyLobbyControl : SLControl
{
    public SLDummyLobbyControl()
    {
        RobustXamlLoader.Load(this);
        LayoutContainer.SetAnchorPreset(Background, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        Lobby.LobbyPlayerMenu.EditCharacter.OnPressed += EditCharacterPressed;
    }

    private void EditCharacterPressed(BaseButton.ButtonEventArgs obj)
    {
        CharacterEditor.Open();
    }

    public void ChangeLobbyBackground(Texture? texture)
    {
        Background.Texture = texture;
    }
}