// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.UI.Core;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby;

[GenerateTypedNameReferences]
public sealed partial class SLDummyLobbyControl : Control
{

    private UIEventHandle _enterEditorHandle;
    private UIEventHandle _exitEditorHandle;
    public SLDummyLobbyControl()
    {
        RobustXamlLoader.Load(this);
        LayoutContainer.SetAnchorPreset(Background, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
    }

    protected override void EnteredTree()
    {
        _enterEditorHandle = UIEvents.Subscribe<EnterCharacterEditorUIEvent>(HandleEnterCharacterEditor);
        _exitEditorHandle = UIEvents.Subscribe<ExitCharacterEditorUIEvent>(HandleExitCharacterEditor);
    }

    private void HandleExitCharacterEditor(ref readonly ExitCharacterEditorUIEvent args)
    {
        Lobby.Visible = true;
    }

    private void HandleEnterCharacterEditor(ref readonly EnterCharacterEditorUIEvent args)
    {
        Lobby.Visible = false;
    }

    protected override void ExitedTree()
    {
        _enterEditorHandle.Unsubscribe();
        _exitEditorHandle.Unsubscribe();
    }
}