// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.Lobby;

[GenerateTypedNameReferences]
public sealed partial class StarlightLobbyLayer : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    public StarlightLobbyLayer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(MainContainer, LayoutContainer.LayoutPreset.Wide);
        SidePanel.SetWidth = _cfg.GetCVar(CCVars.ServerLobbyRightPanelWidth);

        CollapseButton.OnPressed += CollapseSideBar;
        ExpandButton.OnPressed += ExpandSideBar;
    }
    private void ExpandSideBar(BaseButton.ButtonEventArgs obj)
    {
        if (SidePanel.Visible)
            return;
        SidePanel.Visible = true;
        ExpandPanel.Visible = false;
    }

    private void CollapseSideBar(BaseButton.ButtonEventArgs obj)
    {
        if (!SidePanel.Visible)
            return;
        SidePanel.Visible = false;
        ExpandPanel.Visible = true;
    }
}