// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.Character.ProfileSlots;
using Content.Client.Lobby;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using CharacterEditorListEntry = Content.Client._Starlight.Character.Editor.Controls.CharacterEditorListEntry;

namespace Content.Client._Starlight.Character.Editor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorProfileList : UIWidget
{
    [Dependency] private readonly IClientPreferencesManager _preferences = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private SLCharacterProfileSystem _profileSystem = default!;

    public CharacterEditorProfileList()
    {
        RobustXamlLoader.Load(this);
        _profileSystem = EntityManager.System<SLCharacterProfileSystem>();
        NewSlotButton.OnPressed += _ => { CreateNewSlot(); };
        _cfg.OnValueChanged(CCVars.GameMaxCharacterSlots, OnValueChanged, true);
    }

    protected override void AddedToScreen()
    {
        _profileSystem.OnSlotUpdated += OnSlotUpdated;
    }

    protected override void RemovedFromScreen()
    {
        _profileSystem.OnSlotUpdated -= OnSlotUpdated;
    }

    private void OnSlotUpdated(int slotIdx, HumanoidCharacterProfile profile)
    {
        var entry = (CharacterEditorListEntry)CharactersList.GetChild(slotIdx);
        entry.UpdateCharacterProfile(profile);
    }

    public void CreateNewSlot()
    {
        if (!_preferences.ServerDataLoaded) //cannot create a slot if no data is loaded!
            return;
        _profileSystem.CreateNewCharacter(HumanoidCharacterProfile.Random());
        UpdateCreateCharacterButtonLock();
    }

    private void OnValueChanged(int newValue)
    {
        if (newValue < CharactersList.ChildCount)
            for (var i = CharactersList.ChildCount - 1; i >= newValue; i--)
                CharactersList.RemoveChild(i);

        if (newValue <= CharactersList.ChildCount) return;
        for (var i = CharactersList.ChildCount - 1; i < newValue; i++)
        {
            CharactersList.AddChild(new CharacterEditorListEntry());
        }
    }

    private CharacterEditorListEntry GetEntryForSlot(int slot)
    {
        return (CharacterEditorListEntry)CharactersList.GetChild(slot);
    }

    private void UpdateCreateCharacterButtonLock()
    {
        NewSlotButton.Disabled = _profileSystem.SlotsFull;
    }
}