// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.ProfileEditor.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
namespace Content.Client._Starlight.CharacterEditor;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorMainControl : ProfileEditorMainControl<CharacterEditor>
{
    public override Control StepButtonRoot =>  EditorStepSelector;
}