// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.ProfileEditor;
using Content.Client._Starlight.UI;
using Content.Shared._Starlight.CharacterProfiles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorControl : SLControl, IProfileEditorControl
{
    public bool EditorControlsInjected { get; set; }

    public CharacterProfile? LiveProfile { get; set; } = null;
    public Entity<SpriteComponent>? PreviewEntity = null;
    public CharacterPreviewMode PreviewMode = default;

    public bool HasPreviewEntity => PreviewEntity != null;
    public bool ProfileHasChanges => LiveProfile is { HasDirtyData: true };

    private ButtonGroup _stepSelectorGroup = new(false);

    [Access(typeof(CharacterEditorSystem))]
    public CharacterEditorSystem? _editorSystem { get; set; }= null;

    public CharacterEditorControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CharacterSelectorButtons.SelectCharacter.OnToggled += OnSelectCharacterPressed;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        SubscribeUIEvent<SelectCharacterProfileUIEvent>(OnCharacterSelected);
    }

    private void OnSelectCharacterPressed(BaseButton.ButtonToggledEventArgs args)
    {
        TogglePopoutPanel(args.Pressed);
    }

    private void OnCharacterSelected(ref readonly SelectCharacterProfileUIEvent args)
    {
        TogglePopoutPanel(false);
        CharacterSelectorButtons.SelectCharacter.Pressed = false;
    }

    public void TogglePopoutPanel(bool visible)
    {
        if (visible == PopoutPanel.Visible)
            return;
        PopoutPanel.Visible = visible;
    }

    public void RegisterEditorStep(CharacterEditorStep step)
    {
        var newButton = new CharacterEditorStepButton{EditorStep = EditorStepSelector.ChildCount,Group = _stepSelectorGroup};
        if (_stepSelectorGroup.Buttons.Count != 1)
        {
            newButton.Pressed = true;
        }
        newButton.Initialize(EditorStepSelector.ChildCount, step, OnStepSelected);
        EditorStepSelector.AddChild(newButton);
    }

    private void OnStepSelected(int stepIndex)
    {
        if (_editorSystem == null || !_editorSystem.IsEditorStepInRange(stepIndex))
            return;
        _editorSystem.SetEditorStep(this, stepIndex);
    }
}