// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using System.Linq;
using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.CharacterProfiles;
using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Reflection;

namespace Content.Client._Starlight.CharacterEditor;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditor : SLControl
{
    [Dependency] private readonly IDynamicTypeFactory _typeFactory = default!;
    [Dependency] private readonly IReflectionManager _reflectionManager = default!;

    private readonly List<CharacterEditorMode> _editorModes = new();

    [Access(typeof(CharacterEditorMode))]
    public CharacterEditorMode? CurrentEditorMode { get; set; } = null;

    public CharacterEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CreateEditorModes();
        CharacterSelectorButtons.SelectCharacter.OnToggled += OnSelectCharacterPressed;
    }

    protected override void EnteredTree()
    {
        SubscribeUIEvent<SelectCharacterProfileUIEvent>(OnCharacterSelected);
    }

    private void OnSelectCharacterPressed(BaseButton.ButtonToggledEventArgs args)
    {
        TogglePopoutPanel(args.Pressed);
    }

    private void OnCharacterSelected(ref readonly SelectCharacterProfileUIEvent args)
    {
        TogglePopoutPanel(false);
        CharacterSelectorButtons.SelectCharacter.Pressed = false;
    }

    public void TogglePopoutPanel(bool visible)
    {
        if (visible == PopoutPanel.Visible)
            return;
        PopoutPanel.Visible = visible;
    }
    public IEnumerable<CharacterEditorMode> IterateEditorModes()
    {
        foreach (var mode in _editorModes)
            yield return mode;
    }

    public void SetEditorMode(CharacterEditorMode mode)
    {
        if (CurrentEditorMode == mode)
            return;
        CurrentEditorMode?.Deactivate();
        mode.Activate();
    }

    private void CreateEditorModes()
    {
        foreach (var editorType in _reflectionManager.GetAllChildren(typeof(CharacterEditorMode)))
        {
            if (editorType.IsAbstract)
                continue;
            var characterEditor = _typeFactory.CreateInstance<CharacterEditorMode>(editorType);
            characterEditor.Initialize(this);
            _editorModes.Add(characterEditor);
        }

        if (_editorModes.Count == 0)
            return;

        SortModes();
        foreach (var mode in _editorModes)
        {
            EditorModeSelector.AddEditorMode(mode);
        }
        if (CurrentEditorMode == null)
        {
            _editorModes.First().Activate();
        }
    }
    private void SortModes()
    {
        _editorModes.Sort((m1, m2) =>
        {
            if (m1.BeforeModes != null && m1.BeforeModes.Contains(m2.GetType()))
                return -1;
            if (m1.AfterModes != null && m1.AfterModes.Contains(m2.GetType()))
                return 1;

            if (m2.BeforeModes != null && m2.BeforeModes.Contains(m1.GetType()))
                return 1;
            if (m2.AfterModes != null && m2.AfterModes.Contains(m1.GetType()))
                return -1;
            return 0;
        });
    }
}