// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.ProfileEditor;
using Content.Client._Starlight.UI;
using Content.Shared._Starlight.CharacterProfiles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorControl : SLWidget, IProfileEditorControl<CharacterEditorControl>
{
    public bool EditorControlsInjected { get; set; }
    public bool RequireExitConfirmation { get; set; }

    public event Action<CharacterEditorControl, int>? OnStepSelected;
    public event Action<CharacterEditorControl>? OnEntered;
    public event Action<CharacterEditorControl>? OnExited;
    public event Action<CharacterEditorControl>? OnSaveChanges;
    public event Action<CharacterEditorControl, bool>? OnDiscardChanges;

    public void EnterEditor()
    {
        if ( Visible || !IsInsideTree)
            return;
        Visible = true;
        OnEntered?.Invoke(this);
    }

    public void ExitEditor()
    {
        if (!Visible || !IsInsideTree)
            return;
        Visible = false;
        OnExited?.Invoke(this);
    }

    public int CurrentSlot = -1;
    public CharacterProfile? LiveProfile { get; set; } = null;
    public Entity<SpriteComponent>? PreviewEntity = null;
    public CharacterPreviewMode PreviewMode = default;

    public bool HasPreviewEntity => PreviewEntity != null;
    public bool ProfileHasChanges => LiveProfile is { HasDirtyData: true };

    private ButtonGroup _stepSelectorGroup = new(false);

    public CharacterEditorControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void TogglePopoutPanel(bool visible)
    {
        if (visible == PopoutPanel.Visible)
            return;
        PopoutPanel.Visible = visible;
    }

    public void RegisterEditorStep(CharacterEditorStep step)
    {
        var newButton = new CharacterEditorStepButton{Group = _stepSelectorGroup};
        if (_stepSelectorGroup.Buttons.Count != 1)
        {
            newButton.Pressed = true;
        }
        newButton.Initialize(EditorStepSelector.ChildCount, step, OnStepButtonPressed);
        EditorStepSelector.AddChild(newButton);
    }

    private void OnStepButtonPressed(int step)
    {
        OnStepSelected?.Invoke(this, step);
    }

    public void DiscardChanges(bool reloadLiveProfile = false)
    {
        OnDiscardChanges?.Invoke(this, reloadLiveProfile);
    }

    public void SaveChanges()
    {
        OnSaveChanges?.Invoke(this);
    }
}