// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.ProfileEditor.UI;
using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
namespace Content.Client._Starlight.CharacterEditor;

public enum CharacterEditorPanelLayout
{
    Main,
    Side
}

public sealed class CharacterEditorRootControl : ProfileEditorRootControl<CharacterEditor, CharacterEditorMainControl>;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorMainControl : ProfileEditorMainControl<CharacterEditorMainControl, CharacterEditor,CharacterEditorPanelLayout>
{
    protected override Control StepSelectorRoot => EditorStepSelector;

    protected override void InjectPanel(CharacterEditorPanelLayout panelEnum, Control panel)
    {
        switch (panelEnum)
        {
            case CharacterEditorPanelLayout.Main:
                MainPanel.AddChild(panel);
                break;
            case CharacterEditorPanelLayout.Side:
                SidePanel.AddChild(panel);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(panelEnum), panelEnum, null);
        }
    }
}