// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.ProfileEditor.UI;
using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
namespace Content.Client._Starlight.CharacterEditor;

public enum CharacterEditorPanelLayout
{
    Main,
    Side
}

public sealed class CharacterEditorRootControl : ProfileEditorRootControl<CharacterEditor, CharacterEditorMainControl, CharacterEditorPanelLayout>;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorMainControl : ProfileEditorMainControl<CharacterEditor, CharacterEditorPanelLayout>
{
    protected override Control StepSelectorRoot => EditorStepSelector;

    protected override void InjectPanel(CharacterEditorPanelLayout layout, Control newControl)
    {
        switch (layout)
        {
            case CharacterEditorPanelLayout.Main:
                MainPanel.AddChild(newControl);
                break;
            case CharacterEditorPanelLayout.Side:
                SidePanel.AddChild(newControl);
                break;
            default:
                throw new ArgumentOutOfRangeException(nameof(layout), layout, null);
        }
    }
}