using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class SLDropdownPopout : Popup
{
    public SLDropdownPopout()
    {
        RobustXamlLoader.Load(this);
    }
}