// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using System.Linq;
using Content.Client._Starlight.CharacterEditor.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Reflection;
using Serilog;
using SLLobbyLayer = Content.Client._Starlight.Lobby.Layers.SLLobbyLayer;

namespace Content.Client._Starlight.CharacterEditor.Layers;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorLayer : Control
{
    [Dependency] private readonly IDynamicTypeFactory _typeFactory = default!;
    [Dependency] private readonly IReflectionManager _reflectionManager = default!;

    private List<CharacterEditorMode> _editorModes = new();
    public CharacterEditorMode? CurrentEditorMode { get; private set; } = null;

    public CharacterEditorLayer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CreateEditorModes();
        CharacterSelectorButtons.SelectCharacter.OnToggled += OnSelectCharacterPressed;
    }

    private void OnSelectCharacterPressed(BaseButton.ButtonToggledEventArgs args)
    {
        TogglePopoutPanel(args.Pressed);
    }

    protected override void EnteredTree()
    {
        InjectEditorModeControls();
    }

    protected override void ExitedTree()
    {
        CurrentEditorMode = null;
        ClearEditorModeControls();
    }

    private void OnCharacterSelected(ProfileSelectorButton button, ButtonPressedUIEvent ev)
    {
        TogglePopoutPanel(false);
        CharacterSelectorButtons.SelectCharacter.Pressed = false;
    }

    public void TogglePopoutPanel(bool visible)
    {
        if (visible == PopoutPanel.Visible)
            return;
        PopoutPanel.Visible = visible;
    }
    public IEnumerable<CharacterEditorMode> IterateEditorModes()
    {
        foreach (var mode in _editorModes)
            yield return mode;
    }

    private void CreateEditorModes()
    {
        foreach (var editorType in _reflectionManager.GetAllChildren(typeof(CharacterEditorMode)))
        {
            if (editorType.IsAbstract)
                continue;
            var characterEditor = _typeFactory.CreateInstance<CharacterEditorMode>(editorType);
            ((ICharacterEditorMode)characterEditor).Initialize();
            _editorModes.Add(characterEditor);
        }
        SortModes();
        foreach (var mode in _editorModes)
        {
            EditorModeSelector.AddEditorMode(mode);
        }
    }

    private void InjectEditorModeControls()
    {
        foreach (var mode in _editorModes)
            ((ICharacterEditorMode)mode).AddPanelsToUI(MainPanel, SidePanel);
    }

    private void ClearEditorModeControls()
    {
        foreach (var mode in _editorModes)
            ((ICharacterEditorMode)mode).RemovePanelsFromUI();
    }

    private void SortModes()
    {
        _editorModes.Sort((m1, m2) =>
        {
            if (m1.BeforeModes != null && m1.BeforeModes.Contains(m2.GetType()))
                return -1;
            if (m1.AfterModes != null && m1.AfterModes.Contains(m2.GetType()))
                return 1;

            if (m2.BeforeModes != null && m2.BeforeModes.Contains(m1.GetType()))
                return 1;
            if (m2.AfterModes != null && m2.AfterModes.Contains(m1.GetType()))
                return -1;
            return 0;
        });
    }
}