// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using System.Numerics;
using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.CharacterEditor.Widgets;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using SLLobbyLayer = Content.Client._Starlight.Lobby.Layers.SLLobbyLayer;

namespace Content.Client._Starlight.CharacterEditor.Layers;

[GenerateTypedNameReferences]
public sealed partial class SLCharacterEditorLayer : UIScreenLayer
{
    [Dependency] private readonly IDynamicTypeFactory _typeFactory = default!;

    private Dictionary<Type, EditorModeWidget> _editorModes = new();

    private EditorModeWidget? _activeMode = null;

    public SLCharacterEditorLayer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SetAnchorPreset(BackgroundPanel, LayoutPreset.Wide, true);

        EditorModeSelector.OnModeButtonPressed += OnModeButtonPressed;
        EditorModeSelector.OnChildAdded += ModeSelectorChildAdded;
        EditorModeSelector.OnChildRemoved += ModeSelectorChildRemoved;
        SetupInitialState();
    }

    private void SetupInitialState()
    {
        foreach (var button in EditorModeSelector.EnumerateButtons())
        {
            if (button.ModeWidgetType == null)
                continue;
            var modeWidget = CreateEditorModePane(button.ModeWidgetType);
            modeWidget.OnSecondaryLabelUpdated += secondaryString =>
            {
                button.ModeName = secondaryString;
            };
        }

        if (EditorModeSelector.SelectedMode?.ModeWidgetType == null)
            return;
        if (!_editorModes.TryGetValue(EditorModeSelector.SelectedMode.ModeWidgetType, out var mode))
            throw new Exception($"Mode of type:{mode} was not found!");
        mode.Visible = true;
        _activeMode = mode;
    }

    private void OnModeButtonPressed(EditorModeButton editorModeButton)
    {
        if (editorModeButton.ModeWidgetType == _activeMode?.GetType())
            return;
        if (_activeMode != null)
            _activeMode.Visible = false;
        if (editorModeButton.ModeWidgetType == null
            || !_editorModes.TryGetValue(editorModeButton.ModeWidgetType, out var editorMode))
        {
            _activeMode = null;
            return;
        }
        editorMode.Visible = true;
        _activeMode = editorMode;
    }

    private void ModeSelectorChildRemoved(Control child)
    {
        if (child is not EditorModeButton { ModeWidgetType: not null } button) return;
        if (button.ModeWidgetType == null)
            return;
        if (!_editorModes.TryGetValue(button.ModeWidgetType, out var editorMode))
            return;
        editorMode.Orphan();
        _editorModes.Remove(button.ModeWidgetType);
        editorMode.OnSecondaryLabelUpdated = null;
        if (_activeMode?.GetType() == button.ModeWidgetType)
            _activeMode = null;
    }

    private void ModeSelectorChildAdded(Control newChild)
    {
        if (newChild is not EditorModeButton { ModeWidgetType: not null } button) return;
        if (button.ModeWidgetType == null)
            return;
        var modeWidget = CreateEditorModePane(button.ModeWidgetType);
        modeWidget.OnSecondaryLabelUpdated += secondaryString =>
        {
            button.ModeName = secondaryString;
        };
    }

    protected override void AddedToScreen()
    {
        if (ParentScreen == null || !ParentScreen.TryGetLayer<SLLobbyLayer>(out var lobbyLayer, true))
        {
            Log.Error($"Character Editor could not find LobbyLayer to hide!");
            return;
        }
        lobbyLayer.Visible = false;
    }

    protected override void RemovedFromScreen()
    {
        if (ParentScreen == null || !ParentScreen.TryGetLayer<SLLobbyLayer>(out var lobbyLayer, true))
        {
            Log.Error($"Character Editor could not find LobbyLayer to hide!");
            return;
        }
        lobbyLayer.Visible = true;
    }

    private EditorModeWidget CreateEditorModePane(Type widgetType)
    {
        if (_editorModes.ContainsKey(widgetType))
            throw new ArgumentException($"Mode for widget of type:{widgetType} already exists!");
        var modeWidget = (EditorModeWidget)_typeFactory.CreateInstance(widgetType);
        modeWidget.Visible = false;
        EditingPanel.AddChild(modeWidget);
        _editorModes.Add(widgetType, modeWidget);
        return modeWidget;
    }
}