// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.CharacterEditor.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using SLLobbyLayer = Content.Client._Starlight.Lobby.Layers.SLLobbyLayer;

namespace Content.Client._Starlight.CharacterEditor.Layers;

[GenerateTypedNameReferences]
public sealed partial class SLCharacterEditorLayer : UIScreenLayer
{
    [Dependency] private readonly IDynamicTypeFactory _typeFactory = default!;

    private Dictionary<Type, EditorModeWidget> _editorWidgetLookup = new();
    private EditorModeButton? _activeEditorModeButton = null;

    public EditorModeButton ActiveEditorButton
    {
        get
        {
            if (_activeEditorModeButton == null)
                throw new Exception($"tried to get active EditorModeButton on {this} but no EditorModeButtons were present!");
            return _activeEditorModeButton;
        }
        private set
        {
            if (_activeEditorModeButton == value)
                return;
            if (_activeEditorModeButton != null)
                SetEditorWidgetsVisibility(_activeEditorModeButton, false);
            _activeEditorModeButton = value;
            SetEditorWidgetsVisibility(value, true);
        }
    }

    public SLCharacterEditorLayer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SetAnchorPreset(BackgroundPanel, LayoutPreset.Wide, true);

        EditorModeSelector.OnModeButtonPressed += OnModeButtonPressed;
        SetupInitialState();
    }

    private void SetupInitialState()
    {
        foreach (var button in EditorModeSelector.EnumerateButtons())
        {
            EnsureEditorPanel(button, button.PopoutPanelType, PopoutPanel);
            EnsureEditorPanel(button, button.EditingPanelType, EditingPanel);
            EnsureEditorPanel(button, button.DetailsPanelType, DetailsPanel);
            if (_activeEditorModeButton != null) continue;
            _activeEditorModeButton = button;
            SetEditorWidgetsVisibility(button, true);
        }
    }

    private void OnModeButtonPressed(EditorModeButton editorModeButton)
    {
        ActiveEditorButton = editorModeButton;
    }
    protected override void AddedToScreen()
    {
        if (ParentScreen == null || !ParentScreen.TryGetLayer<SLLobbyLayer>(out var lobbyLayer, true))
        {
            Log.Error($"Character Editor could not find LobbyLayer to hide!");
            return;
        }
        lobbyLayer.Visible = false;
    }

    protected override void RemovedFromScreen()
    {
        if (ParentScreen == null || !ParentScreen.TryGetLayer<SLLobbyLayer>(out var lobbyLayer, true))
        {
            Log.Error($"Character Editor could not find LobbyLayer to hide!");
            return;
        }
        lobbyLayer.Visible = true;
    }

    private void SetEditorWidgetsVisibility(EditorModeButton modeButton, bool visible)
    {
        if (modeButton.PopoutPanelType != null)
        {
            _editorWidgetLookup[modeButton.PopoutPanelType].Visible = visible;
        }
        if (modeButton.EditingPanelType != null)
        {
            _editorWidgetLookup[modeButton.EditingPanelType].Visible = visible;
        }
        if (modeButton.PopoutPanelType != null)
        {
            _editorWidgetLookup[modeButton.PopoutPanelType].Visible = visible;
            PopoutPanel.Visible = visible;
        }
    }

    private void EnsureEditorPanel(EditorModeButton button, Type? widgetType, Control panelParent)
    {
        if (widgetType != null)
        {
            if (!_editorWidgetLookup.TryGetValue(widgetType, out var modeWidget))
            {
                modeWidget = (EditorModeWidget)_typeFactory.CreateInstance(widgetType);
                modeWidget.Visible = false;
                panelParent.AddChild(modeWidget);
                _editorWidgetLookup.Add(widgetType, modeWidget);
            }

            modeWidget.LinkButton(button);
        }
    }
}