// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.Character.ProfileSlots;
using Content.Client.Lobby;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.UIEvents;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Character.Editor.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorListEntry : ContainerButton, IUIEventSubscriber
{

    [Dependency] private readonly IClientPreferencesManager _preferences = default!;

    public bool HasProfile { get; private set; }

    public CharacterEditorListEntry()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        EnabledCheck.OnToggled += OnEnabledToggle;
    }

    private void OnEnabledToggle(ButtonToggledEventArgs args)
    {
        if (CharacterView.SlotIdx <= 0)
            return;
        _preferences.SetCharacterEnable(CharacterView.SlotIdx, args.Pressed);
    }

    protected override void EnteredTree()
    {
        CharacterView.SlotIdx = GetPositionInParent();
        UserInterfaceManager.SubscribeGlobalUIEvent<CharacterSlotUpdatedUIEvent>(this, OnCharacterSlotUpdated);
        Refresh();
    }

    protected override void ExitedTree()
    {
        CharacterView.SlotIdx = -1;
    }

    private void OnCharacterSlotUpdated(CharacterSlotUpdatedUIEvent ev)
    {
        if (CharacterView.SlotIdx != ev.SlotIdx)
            return;
        UpdateCharacterProfile(ev.Profile);
    }

    public void Refresh()
    {
        if (_preferences.Preferences == null
            || CharacterView.SlotIdx <= 0)
            return;
        _preferences.Preferences.TryGetHumanoidInSlot(CharacterView.SlotIdx, out var profile);
        UpdateCharacterProfile(profile);
    }


    public void UpdateCharacterProfile(HumanoidCharacterProfile? profile)
    {
        if (profile == null)
        {
            CharacterName.Text = "Urist McPlaceholder";
            CharacterJob.Text = "PlaceholderJob";
            //CharacterView.ClearCharacter();
            Visible = false;
            HasProfile = false;
            return;
        }
        CharacterName.Text = profile.Name;
        //TODO: Jobtext
        // if (!CharacterView.SetFromProfile(profile))
        // {
        //     HasProfile = false;
        //     Visible = false;
        //     Disabled = true;
        //     return;
        // }
        HasProfile = true;
        Visible = true;
        Disabled = false;
    }
}