// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Character.Editor.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorListEntry : ContainerButton
{

    public bool HasProfile { get; private set; }

    public CharacterEditorListEntry()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }


    public void UpdateCharacterProfile(HumanoidCharacterProfile? profile)
    {
        if (profile == null)
        {
            CharacterName.Text = "Urist McPlaceholder";
            CharacterJob.Text = "PlaceholderJob";
            CharacterView.ClearCharacter();
            Visible = false;
            HasProfile = false;
            return;
        }
        CharacterName.Text = profile.Name;
        //TODO: Jobtext
        if (!CharacterView.SetFromProfile(profile))
        {
            HasProfile = false;
            Visible = false;
            return;
        }
        HasProfile = true;
        Visible = true;

    }
}