// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Editors.Appearance;

[GenerateTypedNameReferences]
public sealed partial class AppearancePanel : CharacterEditorPanel
{
    public AppearancePanel()
    {
        RobustXamlLoader.Load(this);
        SetupEditorFields();
    }

    private void SetupEditorFields()
    {
        // CharacterBodyTypeField.InitializeAsEnumField((Sex bodyType, CharacterProfile profile, CharacterIdentityData data) =>
        // {
        //     data.BodyType = bodyType;
        // }, data => data.BodyType);
    }
}