// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Editors.Appearance;

[GenerateTypedNameReferences]
public sealed partial class MarkingsPanel : CharacterEditorRightPanel
{
    public override CharacterEditorStep Step => CharacterEditorStep.Appearance;
    public MarkingsPanel()
    {
        RobustXamlLoader.Load(this);
    }

}