// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Shared._Starlight.CharacterProfiles;
using Content.Shared._Starlight.CharacterProfiles.Data;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;

namespace Content.Client._Starlight.CharacterEditor.Editors.Identity;

[GenerateTypedNameReferences]
public sealed partial class IdentityPanel : CharacterEditorPanel
{

    private const int MinAge = 18;

    public IdentityPanel()
    {
        RobustXamlLoader.Load(this);
        Margin = new Thickness(10);
        NameRuleDisclaimer.Text =
            "Warning: Offensive or LRP IC names will lead\n to admin intervention on this server. \n Read our [Rules] for more.";
        NameRuleDisclaimer.FontColorOverride = Color.Red;
    }
}