// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.CharacterProfiles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterMenuWidget : UIWidget
{
    private CharacterProfileSystem _profileSystem = default!;
    private CharacterEditorSystem _editorSystem = default!;
    public CharacterMenuWidget()
    {
        RobustXamlLoader.Load(this);
        _profileSystem = EntityManager.System<CharacterProfileSystem>();
        CreateCharacter.OnPressed += OnCreateCharacterPressed;
        SelectCharacter.ToggleMode = true;
        SaveChanges.OnPressed += OnSaveChangesPressed;
        DiscardChanges.OnPressed += OnDiscardPressed;
    }

    private void OnDiscardPressed(BaseButton.ButtonEventArgs obj)
    {
        _editorSystem.DiscardChanges();
        SaveChanges.Disabled = true;
    }

    private void OnSaveChangesPressed(BaseButton.ButtonEventArgs obj)
    {
        _editorSystem.ApplyChanges();
        SaveChanges.Disabled = true;
    }

    protected override void EnteredTree()
    {
        SubscribeUIEvent<CharacterEditingHasChangesUIEvent>(OnCharacterDirtied);
    }

    private void OnCharacterDirtied(CharacterEditingHasChangesUIEvent ev)
    {
        SaveChanges.Disabled = false;
    }

    private void OnCreateCharacterPressed(BaseButton.ButtonEventArgs obj)
    {
        _profileSystem.CreateNewCharacter();
    }
}