// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.1

using Content.Client._Starlight.CharacterEditor.Windows;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorMenuBarWidget : CharacterEditorWidget
{
    private readonly CharacterEditorCloseConfirmWindow _closeConfirmWindow;
    public CharacterEditorMenuBarWidget()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += OnClosePressed;
        _closeConfirmWindow = new();
        _closeConfirmWindow.NoSaveButton.OnPressed += ExitWithoutChanges;
        _closeConfirmWindow.SaveButton.OnPressed += ExitWithChanges;
        _closeConfirmWindow.CancelButton.OnPressed += _ => { _closeConfirmWindow.Close(); };
    }

    private void ExitWithChanges(BaseButton.ButtonEventArgs obj)
    {
        _closeConfirmWindow.Close();
        if (OwningEditor == null)
            return;
        RaiseUIEvent(new EditorChangesAppliedUIEvent(OwningEditor));
        RaiseUIEvent(new ExitEditorUIEvent(OwningEditor));
    }

    private void ExitWithoutChanges(BaseButton.ButtonEventArgs obj)
    {
        _closeConfirmWindow.Close();
        if (OwningEditor == null)
            return;
        RaiseUIEvent(new EditorChangesDiscardedUIEvent(OwningEditor));
        RaiseUIEvent(new ExitEditorUIEvent(OwningEditor));
    }

    private void OnClosePressed(BaseButton.ButtonEventArgs obj)
    {
        if (OwningEditor == null)
        {
            _closeConfirmWindow.Close();
            return;
        }
        if (OwningEditor.RequireExitConfirmation)
        {
            if (_closeConfirmWindow.IsOpen)
                return;
            _closeConfirmWindow.OpenCentered();
            return;
        }
        RaiseUIEvent(new ExitEditorUIEvent(OwningEditor));
    }
}