// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using System.Linq;
using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.CharacterProfiles;
using Content.Shared._Starlight.CharacterProfiles.Data;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterSlotSelectorWidget : CharacterEditorWidget
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private ButtonGroup _buttonGroup = new(false);
    private int SlotCount => SelectorButtons.ChildCount;

    public CharacterSlotSelectorWidget()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        if (_buttonGroup.Pressed is ProfileSelectorButton selectorButton)
            selectorButton.ToggleDeleteButton(false);
        _cfg.OnValueChanged(CCVars.GameMaxCharacterSlots, OnValueChanged, true);
        //SubscribeUIEvent<CharacterSlotUpdatedUIEvent>(HandleCharacterProfileUpdated);
    }

    private void HandleCharacterProfileUpdated(ref readonly CharacterSlotUpdatedUIEvent args)
    {
        var name = string.Empty;
        var job = string.Empty;
        if (!args.Deleted)
        {
            var button = EnsureSelectorButton(args.Slot);
            if (args.Profile != null)
            {
                name = args.Profile.GetData<CharacterIdentityData>().Name;
                var proto = args.Profile.GetData<LegacyCharacterData>().LegacyProfile.JobPreferences.FirstOrNull();
                if (proto != null)
                    job = _prototypeManager.Index(proto).LocalizedName;
            }
            button.SetFromData(args.Profile, args.Preview, name, job);
            return;
        }
        if (SlotCount > args.Slot)
            GetButton(args.Slot).SetFromData(args.Profile, args.Preview, name, job);
    }

    private ProfileSelectorButton EnsureSelectorButton(int slot)
    {
        if (SlotCount > slot)
            return (ProfileSelectorButton)SelectorButtons.GetChild(slot);
        var toCreate = slot - SlotCount;
        for (var i = 1; i < toCreate; i++)
        {
            CreateNewSelector();
        }
        return CreateNewSelector();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _cfg.UnsubValueChanged(CCVars.GameMaxCharacterSlots, OnValueChanged);
    }

    private void OnValueChanged(int newMaxCharacters)
    {
        if (SlotCount > newMaxCharacters)
        {
            for (var i = 0; i < SlotCount - newMaxCharacters; i++)
            {
                DeleteSelector(SlotCount - 1);
            }
            return;
        }

        for (var i = 0; i < newMaxCharacters - SlotCount; i++)
        {
            CreateNewSelector();
        }
    }

    private void DeleteSelector(int slot)
    {
        SelectorButtons.RemoveChild(slot);
    }

    private ProfileSelectorButton CreateNewSelector()
    {
        var newButton = new ProfileSelectorButton(){Visible = false};
        SelectorButtons.AddChild(newButton);
        newButton.Group = _buttonGroup;
        return newButton;
    }

    private ProfileSelectorButton GetButton(int slot)
    {
        return (ProfileSelectorButton)SelectorButtons.GetChild(slot);
    }
}