// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client.Lobby;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorProfileList : UIWidget
{
    [Dependency] private readonly IClientPreferencesManager _preferences = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public CharacterEditorProfileList()
    {
        RobustXamlLoader.Load(this);
        _cfg.GetCVar(CCVars.GameMaxCharacterSlots);
        _cfg.OnValueChanged(CCVars.GameMaxCharacterSlots, OnValueChanged);
    }

    private void OnValueChanged(int newValue)
    {
        if (newValue < CharactersList.ChildCount)
            for (var i = CharactersList.ChildCount - 1; i >= newValue; i--)
                CharactersList.RemoveChild(i);

        if (newValue <= CharactersList.ChildCount) return;

        for (var i = CharactersList.ChildCount - 1; i < newValue; i++)
            CharactersList.AddChild(new CharacterEditorListEntry());
    }
}