// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.UI;
using Content.Shared._Starlight.CharacterProfiles;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterSlotSelectorWidget : SLWidget
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private ISawmill Log;
    private Dictionary<int, CharacterProfile> _profiles = new();

    private ButtonGroup _buttonGroup = new(false);

    private int SlotCount => SelectorButtons.ChildCount;

    public CharacterSlotSelectorWidget()
    {
        RobustXamlLoader.Load(this);
        Log = _logManager.GetSawmill(ToString());
        Orientation = LayoutOrientation.Vertical;
    }

    protected override void EnteredTree()
    {
        if (_buttonGroup.Pressed is ProfileSelectorButton selectorButton)
            selectorButton.ToggleDeleteButton(false);
        _cfg.OnValueChanged(CCVars.GameMaxCharacterSlots, OnValueChanged, true);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _cfg.UnsubValueChanged(CCVars.GameMaxCharacterSlots, OnValueChanged);
    }

    private void OnValueChanged(int newMaxCharacters)
    {
        if (SlotCount > newMaxCharacters)
        {
            for (var i = 0; i < SlotCount - newMaxCharacters; i++)
            {
                SelectorButtons.RemoveChild(SlotCount - 1);
            }
            return;
        }

        for (var i = 0; i < newMaxCharacters - SlotCount; i++)
        {
            var newButton = new ProfileSelectorButton();
            SelectorButtons.AddChild(newButton);
            newButton.Group = _buttonGroup;
        }
    }

}