// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterMenuWidget : CharacterEditorWidget
{
    public CharacterMenuWidget()
    {
        RobustXamlLoader.Load(this);
        SelectCharacter.ToggleMode = true;
        SelectCharacter.OnPressed += HandleSelectCharacter;
        SaveChanges.OnPressed += SaveChangesPressed;
        DiscardChanges.OnPressed += DiscardPressed;
    }

    private void HandleSelectCharacter(BaseButton.ButtonEventArgs obj)
    {
        //TODO: select character confirmation so that you can't discard changes by accident
        OwningEditor?.TogglePopoutPanel(true);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        SubscribeUIEvent<EditorIsDirtyUIEvent>(HandleEditorDirtied);
        SubscribeUIEvent<EditorChangesAppliedUIEvent>(HandleChangesApplied);
        SubscribeUIEvent<EditorChangesDiscardedUIEvent>(HandleChangesDiscarded);
    }

    private void HandleChangesDiscarded(ref readonly EditorChangesDiscardedUIEvent args)
    {
        SaveChanges.Disabled = true;
        DiscardChanges.Disabled = true;
    }

    private void HandleChangesApplied(ref readonly EditorChangesAppliedUIEvent args)
    {
        SaveChanges.Disabled = true;
        DiscardChanges.Disabled = true;
    }

    private void HandleEditorDirtied(ref readonly EditorIsDirtyUIEvent args)
    {
        SaveChanges.Disabled = false;
        DiscardChanges.Disabled = false;
    }


    private void DiscardPressed(BaseButton.ButtonEventArgs obj)
    {
        if (OwningEditor != null)
            RaiseUIEvent(new EditorChangesDiscardedUIEvent(OwningEditor));
    }

    private void SaveChangesPressed(BaseButton.ButtonEventArgs obj)
    {
        if (OwningEditor != null)
            RaiseUIEvent(new EditorChangesAppliedUIEvent(OwningEditor));
    }
}