// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.CharacterEditor.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterPreviewWidget : UIWidget
{
    private CharacterEditorSystem editorSystem = default!;

    private List<string> _previewModeLocStrings = new();
    public CharacterPreviewWidget()
    {
        RobustXamlLoader.Load(this);
        editorSystem = EntityManager.System<CharacterEditorSystem>();

        ViewRight.OnPressed += OnShiftViewRight;
        ViewLeft.OnPressed += OnShiftViewLeft;
        CharacterSpritePreview.OverrideDirection = Direction.South;

        SelectedView.Text = CharacterEditorHelpers.GetLocalizedPreviewMode(default);
        foreach (var mode in Enum.GetValues<CharacterPreviewMode>())
        {
            var newOption = new CharacterPreviewModeButton();
            newOption.PreviewMode = mode;
            var locId = CharacterEditorHelpers.GetLocalizedPreviewMode(mode);
            _previewModeLocStrings.Add(locId);
            newOption.Text = locId;
            ViewSelector.AddDropdownOption(newOption);
            newOption.OnPressed += PreviewModeButtonPressed;
        }
    }

    private void PreviewModeButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        var modeButton = (CharacterPreviewModeButton)obj.Button;
        editorSystem.ChangePreviewMode(modeButton.PreviewMode);
    }

    private void OnShiftViewLeft(BaseButton.ButtonEventArgs obj)
    {
        switch (CharacterSpritePreview.OverrideDirection)
        {
            case Direction.South:
                CharacterSpritePreview.OverrideDirection = Direction.West;
                break;
            case Direction.East:
                CharacterSpritePreview.OverrideDirection = Direction.South;
                break;
            case Direction.North:
                CharacterSpritePreview.OverrideDirection = Direction.East;
                break;
            case Direction.West:
                CharacterSpritePreview.OverrideDirection = Direction.North;
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    private void OnShiftViewRight(BaseButton.ButtonEventArgs args)
    {
        switch (CharacterSpritePreview.OverrideDirection)
        {
            case Direction.South:
                CharacterSpritePreview.OverrideDirection = Direction.East;
                break;
            case Direction.East:
                CharacterSpritePreview.OverrideDirection = Direction.North;
                break;
            case Direction.North:
                CharacterSpritePreview.OverrideDirection = Direction.West;
                break;
            case Direction.West:
                CharacterSpritePreview.OverrideDirection = Direction.South;
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    protected override void EnteredTree()
    {
        SubscribeGlobalUIEvent<LiveCharacterProfileUpdatedUIEvent>(OnLiveProfileUpdated);
        SubscribeGlobalUIEvent<LiveCharacterPreviewModeUpdatedUIEvent>(OnPreviewModeUpdated);
    }

    private void OnPreviewModeUpdated(LiveCharacterPreviewModeUpdatedUIEvent ev)
    {
        SelectedView.Text = _previewModeLocStrings[(int)ev.NewMode];
    }

    private void OnLiveProfileUpdated(LiveCharacterProfileUpdatedUIEvent ev)
    {
        CharacterName.Text = ev.Profile.Comp1.Data.Profile.Name;
        CharacterSpritePreview.SetEntity(ev.Profile);
    }
}