// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.1

using Content.Client._Starlight.CharacterEditor.Windows;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorMenuBarWidget : CharacterEditorWidget
{
    private readonly CharacterEditorCloseConfirmWindow _closeConfirmWindow;

    public event Action<bool>? OnClosePressed;

    public bool HasChanges { get; private set; }

    public CharacterEditorMenuBarWidget()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += OpenClosePrompt;
        _closeConfirmWindow = new();
        _closeConfirmWindow.NoSaveButton.OnPressed += ExitWithoutChanges;
        _closeConfirmWindow.SaveButton.OnPressed += ExitWithChanges;
        _closeConfirmWindow.CancelButton.OnPressed += _ => { _closeConfirmWindow.Close(); };
    }

    private void ExitWithChanges(BaseButton.ButtonEventArgs? obj = null)
    {
        _closeConfirmWindow.Close();
        OnClosePressed?.Invoke(true);
    }

    private void ExitWithoutChanges(BaseButton.ButtonEventArgs? obj = null)
    {
        _closeConfirmWindow.Close();
        OnClosePressed?.Invoke(false);
    }

    private void OpenClosePrompt(BaseButton.ButtonEventArgs obj)
    {
        if (!HasChanges)
        {
            _closeConfirmWindow.Close();
            ExitWithoutChanges();
            return;
        }
        _closeConfirmWindow.OpenCentered();
        return;
    }
}