// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.UI;
using Content.Client._Starlight.UI.Core;
using Content.Shared._Starlight.CharacterProfiles;
using Content.Shared._Starlight.CharacterProfiles.Data;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterPreviewWidget : SLWidget
{
    public CharacterPreviewWidget()
    {
        RobustXamlLoader.Load(this);
        ViewRight.OnPressed += OnShiftViewRight;
        ViewLeft.OnPressed += OnShiftViewLeft;
        EditName.OnToggled += OnEditName;
        CharacterSpritePreview.OverrideDirection = Direction.South;
        SetupDropdown();

        NameRuleDisclaimer.Text =
            "Warning: Offensive or LRP IC names \n will lead to admin intervention on this server. \n Read our [Rules] for more.";
        NameRuleDisclaimer.FontColorOverride = Color.Red;
        CharacterNameEditor.Margin = new Thickness(10, 0);
    }


    private void OnShiftViewLeft(BaseButton.ButtonEventArgs obj)
    {
        switch (CharacterSpritePreview.OverrideDirection)
        {
            case Direction.South:
                CharacterSpritePreview.OverrideDirection = Direction.West;
                break;
            case Direction.East:
                CharacterSpritePreview.OverrideDirection = Direction.South;
                break;
            case Direction.North:
                CharacterSpritePreview.OverrideDirection = Direction.East;
                break;
            case Direction.West:
                CharacterSpritePreview.OverrideDirection = Direction.North;
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    private void OnShiftViewRight(BaseButton.ButtonEventArgs args)
    {
        switch (CharacterSpritePreview.OverrideDirection)
        {
            case Direction.South:
                CharacterSpritePreview.OverrideDirection = Direction.East;
                break;
            case Direction.East:
                CharacterSpritePreview.OverrideDirection = Direction.North;
                break;
            case Direction.North:
                CharacterSpritePreview.OverrideDirection = Direction.West;
                break;
            case Direction.West:
                CharacterSpritePreview.OverrideDirection = Direction.South;
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }
    }

    protected override void EnteredTree()
    {
        SubscribeUIEvent<CharacterEditorPreviewChangedUIEvent>(OnPreviewUpdated);
        SubscribeUIEvent<CharacterEditorProfileDirtiedUIEvent>(OnProfileDirtied);
    }

    private void OnProfileDirtied(ref readonly CharacterEditorProfileDirtiedUIEvent args)
    {
        CharacterName.Text = args.Profile.GetData<LegacyCharacterData>().LegacyProfile.Name;
    }

    private void OnPreviewUpdated(ref readonly CharacterEditorPreviewChangedUIEvent args)
    {
        CharacterSpritePreview.SetEntity(args.PreviewEntity);
    }

    private void SetupDropdown()
    {
        var locPrefix = "character-editor-preview-mode-";
        var labels = Enum.GetNames<CharacterPreviewMode>();
        for (var i = 0; i < labels.Length; i++)
            PreviewMode.AddItem(Loc.GetString(locPrefix+(labels[i].ToLower())), i);
        PreviewMode.OnItemSelected += HandlePreviewModeSelected;
    }

    private void HandlePreviewModeSelected(OptionButton.ItemSelectedEventArgs obj)
    {
        RaiseUIEvent(new ChangeCharacterEditorPreviewModeUIEvent((CharacterPreviewMode)obj.Id));
        obj.Button.Select(obj.Id);
    }


    private void OnEditName(BaseButton.ButtonToggledEventArgs args)
    {
        if (args.Pressed)
        {
            RandomizeFirstName.Disabled = false;
            RandomizeNickname.Disabled = false;
            RandomizeLastName.Disabled = false;
            FirstNameField.Editable = true;
            CharacterNameEditor.Visible = true;
            CharacterName.Visible = false;
            if (CharacterName.Text != null)
                FirstNameField.SetText(CharacterName.Text);
            return;
        }
        RandomizeFirstName.Disabled = true;
        RandomizeNickname.Disabled = true;
        RandomizeLastName.Disabled = true;
        CharacterNameEditor.Visible = false;
        CharacterName.Visible = true;
        FirstNameField.Editable = false;
        var nickname = "";
        if (NicknameField.Text.Length > 0)
            nickname = $" '{NicknameField.Text}'";

        var lastName = "";
        if (LastnameField.Text.Length > 0)
            lastName = $" '{LastnameField.Text}'";
        CharacterName.Text = $"{FirstNameField.Text}{nickname}{lastName}";

        var profile = new EditCharacterProfileFieldUIRequest(null);
        UIEvents.RaiseRequest(ref profile);
        profile.Profile?.EditData(CharacterName.Text, (string name, ref CharacterIdentityData data) =>
        {
            data.Name = name;
            return true;
        });
        profile.Profile?.EditData(CharacterName.Text,(string name, ref LegacyCharacterData data) =>
        {
            data.LegacyProfile.Name = name;
            return true;
        });
        if ( profile.Profile != null)
            UIEvents.RaiseEvent(new CharacterEditorProfileDirtiedUIEvent(profile.Profile));
    }

}