// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.1

using Content.Client._Starlight.CharacterEditor.Layers;
using Content.Client.Lobby.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorMenuBarWidget : UIWidget
{
    public bool RequireConfirmation { get; set; } = false;

    private CharacterSetupGuiSavePanel _closeConfirmWindow;
    public CharacterEditorMenuBarWidget()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += OnClosePressed;
        _closeConfirmWindow = new();
        _closeConfirmWindow.NoSaveButton.OnPressed += ExitWithoutChanges;
        _closeConfirmWindow.SaveButton.OnPressed += ExitWithChanges;
        _closeConfirmWindow.CancelButton.OnPressed += _ => { _closeConfirmWindow.Close(); };
    }

    private void ExitCharacterEditor()
    {
        _closeConfirmWindow.Close();
        UserInterfaceManager.ActiveScreen?.DisableLayer<SLCharacterEditorLayer>();
    }

    private void ExitWithChanges(BaseButton.ButtonEventArgs obj)
    {
        //TODO: apply changes
        ExitCharacterEditor();
    }

    private void ExitWithoutChanges(BaseButton.ButtonEventArgs obj)
    {
        //TODO: drop changes
        ExitCharacterEditor();
    }

    private void OnClosePressed(BaseButton.ButtonEventArgs obj)
    {
        if (RequireConfirmation)
        {
            if (_closeConfirmWindow.IsOpen)
                return;
            _closeConfirmWindow.OpenCentered();
            return;
        }
        ExitCharacterEditor();
    }
}