// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CharacterSlotSelectorWidget : UIWidget
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private ButtonGroup _buttonGroup = new(false);

    private int SlotCount => ListEntries.ChildCount;

    public CharacterSlotSelectorWidget()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        _cfg.OnValueChanged(CCVars.GameMaxCharacterSlots, OnValueChanged, true);
        _buttonGroup.OnUnPressed += button =>
        {
            if (button is ProfileSelectorButton selector)
                selector.ToggleDeleteButton(true);
        };
    }

    private void OnValueChanged(int newMaxCharacters)
    {
        if (SlotCount > newMaxCharacters)
        {
            for (var i = 0; i < SlotCount - newMaxCharacters; i++)
                ListEntries.RemoveChild(SlotCount - 1);
            return;
        }

        for (var i = 0; i < newMaxCharacters - SlotCount; i++)
        {
            var newSelector = new ProfileSelectorButton {Slot = i};
            ListEntries.AddChild(newSelector);
            newSelector.OnPressed += args => ((ProfileSelectorButton)args.Button).ToggleDeleteButton(false);
            newSelector.Group = _buttonGroup;
        }
    }

    protected override void EnteredTree()
    {
        if (_buttonGroup.Pressed is ProfileSelectorButton selectorButton)
            selectorButton.ToggleDeleteButton(false);
    }
}