// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class EditorModeList : SLWidget
{
    private ButtonGroup _modeSelectorGroup;
    public EditorModeList()
    {
        RobustXamlLoader.Load(this);
        _modeSelectorGroup = new(false);
    }
    public void AddEditorMode(CharacterEditorMode mode)
    {
        var newButton = new CharacterEditorModeButton{EditorMode = mode,Group = _modeSelectorGroup};
        if (_modeSelectorGroup.Buttons.Count != 1) return; //don't continue if we aren't the first mode/button added
        newButton.Pressed = true;
    }
}