// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class EditorModeList : UIWidget
{

    private EditorModeButton? _selectedMode = null;

    public EditorModeButton? SelectedMode
    {
        get => _selectedMode;
        private set
        {
            if (_selectedMode == value)
                return;
            if (value == null)
                throw new ArgumentException("Cannot change selected editor mode to null! " +
                                            "One must always be selected!");

            var oldbutton = _selectedMode;
            _selectedMode = value;
            if (oldbutton != null)
                oldbutton.Disabled = false;
            value.Disabled = true;
            OnModeButtonPressed?.Invoke(value);
        }
    }

    public event Action<EditorModeButton>? OnModeButtonPressed;

    public EditorModeList()
    {
        RobustXamlLoader.Load(this);
    }

    public IEnumerable<EditorModeButton> EnumerateButtons()
    {
        foreach (var control in Children)
            if (control is EditorModeButton button)
                yield return button;
    }

    protected override void ChildAdded(Control newChild)
    {
        base.ChildAdded(newChild);

        if (newChild is not EditorModeButton modeButton) return;
        modeButton.OnPressed += args =>
        {
            if (SelectedMode == modeButton) return;
            SelectedMode = modeButton;
        };
        SelectedMode ??= modeButton;
    }
}