// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Starlight.CharacterEditor.Widgets;

[GenerateTypedNameReferences]
public sealed partial class EditorModeList : UIWidget
{
    private ButtonGroup _modeSelectorGroup;
    public EditorModeList()
    {
        RobustXamlLoader.Load(this);
        _modeSelectorGroup = new(false);
        _modeSelectorGroup.OnUnPressed += HandleDeselect;
    }

    private void HandleDeselect(BaseButton obj)
    {
        var editorMode = ((EditorModeButton)obj).EditorMode;
        RaiseUIEvent(new CharacterEditorModeExitedUIEvent(editorMode));
    }

    private void HandleModeSelection(BaseButton.ButtonEventArgs obj)
    {
        var editorMode = ((EditorModeButton)obj.Button).EditorMode;
        RaiseUIEvent(new CharacterEditorModeEnteredUIEvent(editorMode));
    }

    public void AddEditorMode(CharacterEditorMode mode)
    {
        var newButton = new EditorModeButton{EditorMode = mode,Group = _modeSelectorGroup};
        newButton.OnPressed += HandleModeSelection;
        if (_modeSelectorGroup.Buttons.Count != 1) return; //don't continue if we aren't the first mode/button added
        RaiseUIEvent(new CharacterEditorModeEnteredUIEvent(newButton.EditorMode));
    }
}