// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.Audio;
using Content.Client.Message;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbySecondaryInfoWidget : UIWidget
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    private ContentAudioSystem _contentAudioSystem = default!;
    public LobbySecondaryInfoWidget()
    {
        RobustXamlLoader.Load(this);
        ReportButton.URI = _cfg.GetCVar(CCVars.InfoLinksBugReport);
        _contentAudioSystem = EntityManager.System<ContentAudioSystem>();
    }

    protected override void AddedToScreen()
    {
        _contentAudioSystem.LobbySoundtrackChanged += UpdateLobbySoundtrackInfo;
    }

    protected override void RemovedFromScreen()
    {
        _contentAudioSystem.LobbySoundtrackChanged -= UpdateLobbySoundtrackInfo;
    }

    private void UpdateLobbyTrackInfo(string? filename)
    {
        if (filename == null)
        {
            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
        }
        else if (
            _resourceCache.TryGetResource<AudioResource>(filename, out var lobbySongResource)
        )
        {
            var lobbyStream = lobbySongResource.AudioStream;

            var title = string.IsNullOrEmpty(lobbyStream.Title)
                ? Loc.GetString("lobby-state-song-unknown-title")
                : lobbyStream.Title;

            var artist = string.IsNullOrEmpty(lobbyStream.Artist)
                ? Loc.GetString("lobby-state-song-unknown-artist")
                : lobbyStream.Artist;

            var markup = Loc.GetString("lobby-state-song-text",
                ("songTitle", title),
                ("songArtist", artist));

            LobbySong.SetMarkup(markup);
        }
    }

    //TODO: eventually this won't be needed when the lobby soundtrack system gets rewritten to not be terrible
    private void UpdateLobbySoundtrackInfo(LobbySoundtrackChangedEvent ev)
    {
        UpdateLobbyTrackInfo(ev.SoundtrackFilename);
    }
}