// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.UserInterface.Systems.Bwoink;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbyMenuBarWidget : UIWidget
{
    public LobbyMenuBarWidget()
    {
        RobustXamlLoader.Load(this);
        var optionsUIController = UserInterfaceManager.GetUIController<OptionsUIController>();
        var ahelpUIController = UserInterfaceManager.GetUIController<AHelpUIController>();
        var mHelpUIController = UserInterfaceManager.GetUIController<MHelpUIController>();

        OptionsButton.OnPressed += _ => optionsUIController.ToggleWindow();
        AHelpButton.OnPressed += _ => ahelpUIController.ToggleWindow();
        MHelpButton.OnPressed += _ => mHelpUIController.ToggleWindow();
    }
}