// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbyPlayerBarWidget : UIWidget
{
    public int ButtonsPerRow { get => PlayerButtonGrid.Columns; set => PlayerButtonGrid.Columns = value; }
    public LobbyPlayerBarWidget()
    {
        RobustXamlLoader.Load(this);
    }
}