// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbyInfoWidget : SLWidget<LobbyInfoWidget, LobbyInfoWidgetSystem>
{
    public LobbyInfoWidget()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateInfoBlob(string? infoBlob)
    {
        if (infoBlob == null)
        {
            ServerInfoText.Text = null;
            return;
        }
        ServerInfoText.SetMessage(FormattedMessage.FromMarkupOrThrow(infoBlob));
    }

    public void UpdateTimer(bool gameStarted, TimeSpan currentTime, TimeSpan roundStartTimeSpan)
    {
        if (gameStarted)
        {
            var roundTime = currentTime.Subtract(roundStartTimeSpan);
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }
        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");
    }
}