// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbyMenuBarWidget : UIWidget
{
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    public LobbyMenuBarWidget()
    {
        RobustXamlLoader.Load(this);
        LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
        OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
    }
}