// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.Administration.Managers;
using Content.Client.Info;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbyLinkBannerWidget : UIWidget
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly INullLinkPlayerRolesManager _playerRoles = default!;

    public int ButtonColumns { get=> LinkBannerButtonGrid.Columns; set => LinkBannerButtonGrid.Columns = value; }
    public LobbyLinkBannerWidget()
    {
        RobustXamlLoader.Load(this);

        var changelogController = UserInterfaceManager.GetUIController<ChangelogUIController>();
        ChangelogButton.OnPressed += args => { changelogController.ToggleWindow();};

        DiscordButton.URI = _cfg.GetCVar(CCVars.InfoLinksDiscord);
        WebsiteButton.URI = _cfg.GetCVar(CCVars.InfoLinksWebsite);
        WikiButton.URI = _cfg.GetCVar(CCVars.InfoLinksWiki);
        ForumButton.URI = _cfg.GetCVar(CCVars.InfoLinksForum);
        TelegramButton.URI = _cfg.GetCVar(CCVars.InfoLinksTelegram);
        LinkDiscord.URI =  _playerRoles.GetDiscordLink();
    }
}