// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.CharacterEditor;
using Content.Client._Starlight.UI;
using Content.Client._Starlight.UI.Core;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbyPlayerBarWidget : SLWidget
{
    public int ButtonsPerRow { get => PlayerButtonGrid.Columns; set => PlayerButtonGrid.Columns = value; }

    public CharacterEditorMainControl? CharacterEditor = null;
    public LobbyPlayerBarWidget()
    {
        RobustXamlLoader.Load(this);
        EditCharacter.OnPressed += HandlePressed;
    }

    private void HandlePressed(BaseButton.ButtonEventArgs obj)
    {
        CharacterEditor?.EnterEditor();
    }
}