// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.UI;
using Content.Client._Starlight.UI.Controls;
using Content.Client.Message;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbySecondaryInfoWidget : SLWidget
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    public LobbySecondaryInfoWidget()
    {
        RobustXamlLoader.Load(this);
        ReportButton.URI = _cfg.GetCVar(CCVars.InfoLinksBugReport);
    }

    private void OnLobbyMusicUpdated(ref readonly LobbyMusicUpdatedUIEvent args)
    {
        if (!args.HasSong)
        {
            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            return;
        }
        LobbySong.SetMarkup( Loc.GetString("lobby-state-song-text",
            ("songTitle", args.Title),
            ("songArtist", args.Artist)));
    }
}