// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Shared.Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbyServerNameWidget : UIWidget
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    public LobbyServerNameWidget()
    {
        RobustXamlLoader.Load(this);
        _cfg.OnValueChanged(StarlightCCVars.ServerName, OnServerNameChanged, true);
        ServerName.Text = Loc.GetString("ui-lobby-welcome", ("name", _cfg.GetCVar(StarlightCCVars.ServerName)));
    }

    private void OnServerNameChanged(string newValue, in CVarChangeInfo info)
    {
        ServerName.Text = Loc.GetString("ui-lobby-welcome", ("name", (string)info.NewValue));
    }
}