// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class LobbyInfoWidget : SLWidget
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    private bool _gameStarted = false;
    private TimeSpan _roundStartTimeSpan;

    public LobbyInfoWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void EnteredTree()
    {
        SubscribeUIEvent<LobbyInfoUpdatedUIEvent>(OnLobbyInfoUpdated);
        SubscribeUIEvent<RoundStartTimeChangedUIEvent>(OnStartTimeChanged);
        SubscribeUIEvent<RoundStateChangedUIEvent>(OnRoundStateChanged);
    }

    private void OnStartTimeChanged(ref readonly RoundStartTimeChangedUIEvent args)
    {
        _roundStartTimeSpan = args.StartTime;
    }

    private void OnRoundStateChanged(ref readonly RoundStateChangedUIEvent args)
    {
        _gameStarted = args.Started;
    }
    private void OnLobbyInfoUpdated(ref readonly LobbyInfoUpdatedUIEvent args)
    {
        if (args.NewInfo == null)
        {
            ServerInfoText.Text = null;
            return;
        }
        ServerInfoText.SetMessage(FormattedMessage.FromMarkupOrThrow(args.NewInfo));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_gameStarted)
        {
            var roundTime =  _gameTiming.CurTime.Subtract(_roundStartTimeSpan);
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }
        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");
    }
}