// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0
// Modified from a file licensed under MIT (Space Wizards Federation)
using Content.Client.GameTicking.Managers;
using Content.Client.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ReadyWidget : UIWidget
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IClientPreferencesManager _preferences = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

    private ClientGameTicker _gameTicker = default!;
    private bool _readyPossibleWithCharacters = false;

    public Action? OnLateJoinReady = null;

    public ReadyWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ReadyButton.TooltipSupplier = GetReadyButtonTooltip;
        ReadyButton.OnPressed += OnReadyPressed;
        ReadyButton.OnToggled += OnReadyToggled;
        //UpdateButtons();
    }

    public void LoadDependencies()
    {
        _gameTicker = _entityManager.System<ClientGameTicker>();
        RoundTimer.LoadDependencies();
        UpdateButtons();
    }

    private void OnReadyToggled(BaseButton.ButtonToggledEventArgs args)
    {
        SetReady(args.Pressed);
    }

    private void OnReadyPressed(BaseButton.ButtonEventArgs obj)
    {
        if (!_gameTicker.IsGameStarted)
        {
            return;
        }
        OnLateJoinReady?.Invoke();
    }

    public void SetReady(bool newReady)
    {
        if (_gameTicker.IsGameStarted)
        {
            return;
        }
        _consoleHost.ExecuteCommand($"toggleready {newReady}");
        UpdateButtons();
    }

    public void UpdateButtons()
    {
        RoundTimer.UpdateTimer();
         if (_gameTicker.IsGameStarted)
         {
             ReadyButton.Text = Loc.GetString("lobby-state-ready-button-join-state");
             ReadyButton.ToggleMode = false;
             ReadyButton.Pressed = false;
             ReadyButton.Disabled = false;
             ObserveButton.Disabled = false;
         }
         else
         {
             ReadyButton.Text = Loc.GetString(ReadyButton.Pressed ? "lobby-state-player-status-ready": "lobby-state-player-status-not-ready");
             // If there is a tooltip showing, make sure to update the text in it as well!
             if (ReadyButton.SuppliedTooltip is Tooltip tooltip)
             {
                 tooltip.Text = GetReadyButtonTooltipText();
             }
             ReadyButton.ToggleMode = true;
             ReadyButton.Disabled = !_readyPossibleWithCharacters;
             ReadyButton.Pressed = _gameTicker.AreWeReady;
             ObserveButton.Disabled = true;
         }


         // if (_gameTicker.ServerInfoBlob != null)
         // {
         //     Lobby!.ServerInfo.SetInfoBlob(_gameTicker.ServerInfoBlob);
         // }

         // var minutesToday = _playtimeTracking.PlaytimeMinutesToday;
         // if (minutesToday > 60)
         // {
         //     Lobby!.PlaytimeComment.Visible = true;
         //
         //     var hoursToday = Math.Round(minutesToday / 60f, 1);
         //
         //     var chosenString = minutesToday switch
         //     {
         //         < 180 => "lobby-state-playtime-comment-normal",
         //         < 360 => "lobby-state-playtime-comment-concerning",
         //         < 720 => "lobby-state-playtime-comment-grasstouchless",
         //         _ => "lobby-state-playtime-comment-selfdestructive"
         //     };
         //
         //     //Lobby.PlaytimeComment.SetMarkup(Loc.GetString(chosenString, ("hours", hoursToday)));
         // }
         // else
         //     //Lobby!.PlaytimeComment.Visible = false;
    }

    private string GetReadyButtonTooltipText()
    {
        if (ReadyButton.ToggleMode)
            return Loc.GetString("ui-lobby-ready-button-tooltip-join-state");
        if (!_preferences.ServerDataLoaded)
            return Loc.GetString("ui-lobby-ready-button-tooltip-not-loaded");
        if ((_preferences.Preferences?.JobPrioritiesFiltered().Count ?? 0) == 0)
            return Loc.GetString("ui-lobby-ready-button-tooltip-no-possible-characters");
        if (ReadyButton.Pressed)
            return Loc.GetString("ui-lobby-ready-button-tooltip-is-ready");
        return Loc.GetString("ui-lobby-ready-button-tooltip-is-not-ready");
    }

    private Control GetReadyButtonTooltip(Control sender)
    {
        return new Tooltip { Text = GetReadyButtonTooltipText() };
    }
}