// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RoundTimerWidget : SLWidget
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    private TimeSpan _roundStartTime;
    private bool _isStarted = false;
    private bool _isPaused = false;

    public RoundTimerWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }


    protected override void EnteredTree()
    {
        SubscribeUIEvent<RoundStateChangedUIEvent>(OnRoundStateChanged);
        SubscribeUIEvent<RoundStartTimeChangedUIEvent>(OnRoundStartTimeChanged);
    }

    private void OnRoundStartTimeChanged(ref readonly RoundStartTimeChangedUIEvent args)
    {
        _roundStartTime = args.StartTime;
    }

    private void OnRoundStateChanged(ref readonly RoundStateChangedUIEvent args)
    {
        _isStarted = args.Started;
        _isPaused = args.Paused;
    }

    public void Update(TimeSpan roundStartTimeSpan)
    {
        if (_isStarted)
        {
            StartTime.Text = string.Empty;
            var roundTime = _gameTiming.CurTime.Subtract(_roundStartTime);
            StartTime.Text = string.Empty;
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }
        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");

        string text;

        if (_isPaused)
        {
            text = Loc.GetString("lobby-state-paused");
        }
        else if (_roundStartTime < _gameTiming.CurTime)
        {
            StartTime.Text = Loc.GetString("lobby-state-soon");
            return;
        }
        else
        {
            var difference = _roundStartTime - _gameTiming.CurTime;
            var seconds = difference.TotalSeconds;
            if (seconds < 0)
            {
                text = Loc.GetString(seconds < -5 ? "lobby-state-right-now-question" : "lobby-state-right-now-confirmation");
            }
            else if (difference.TotalHours >= 1)
            {
                text = $"{Math.Floor(difference.TotalHours)}:{difference.Minutes:D2}:{difference.Seconds:D2}";
            }
            else
            {
                text = $"{difference.Minutes}:{difference.Seconds:D2}";
            }
        }
        StartTime.Text = Loc.GetString("lobby-state-round-start-countdown-text", ("timeLeft", text));
    }
}