// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client.GameTicking.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RoundTimerWidget : UIWidget
{
    [Dependency] private IGameTiming _gameTiming = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private ClientGameTicker _gameTicker = default!;
    public RoundTimerWidget()
    {
        RobustXamlLoader.Load(this);
        _gameTicker = _entityManager.System<ClientGameTicker>();
    }

    public void TickTimer()
    {
        if (_gameTicker.IsGameStarted)
        {
            StartTime.Text = string.Empty;
            var roundTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }
        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");

        string text;

        if (_gameTicker.Paused)
        {
            text = Loc.GetString("lobby-state-paused");
        }
        else if (_gameTicker.StartTime < _gameTiming.CurTime)
        {
            StartTime.Text = Loc.GetString("lobby-state-soon");
            return;
        }
        else
        {
            var difference = _gameTicker.StartTime - _gameTiming.CurTime;
            var seconds = difference.TotalSeconds;
            if (seconds < 0)
            {
                text = Loc.GetString(seconds < -5 ? "lobby-state-right-now-question" : "lobby-state-right-now-confirmation");
            }
            else if (difference.TotalHours >= 1)
            {
                text = $"{Math.Floor(difference.TotalHours)}:{difference.Minutes:D2}:{difference.Seconds:D2}";
            }
            else
            {
                text = $"{difference.Minutes}:{difference.Seconds:D2}";
            }
        }
        StartTime.Text = Loc.GetString("lobby-state-round-start-countdown-text", ("timeLeft", text));
    }
}