// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Lobby.Widgets;

[GenerateTypedNameReferences]
public sealed partial class RoundTimerWidget : SLWidget<RoundTimerWidget, RoundTimerWidgetSystem>
{
    public RoundTimerWidget()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(bool isStarted, bool isPaused, TimeSpan roundStartTimeSpan, TimeSpan currentTime,
        TimeSpan startTime)
    {
        if (isStarted)
        {
            StartTime.Text = string.Empty;
            var roundTime = currentTime.Subtract(roundStartTimeSpan);
            StartTime.Text = string.Empty;
            StationTime.Text = Loc.GetString("lobby-state-player-status-round-time", ("hours", roundTime.Hours), ("minutes", roundTime.Minutes));
            return;
        }
        StationTime.Text = Loc.GetString("lobby-state-player-status-round-not-started");

        string text;

        if (isPaused)
        {
            text = Loc.GetString("lobby-state-paused");
        }
        else if (startTime < currentTime)
        {
            StartTime.Text = Loc.GetString("lobby-state-soon");
            return;
        }
        else
        {
            var difference = startTime - currentTime;
            var seconds = difference.TotalSeconds;
            if (seconds < 0)
            {
                text = Loc.GetString(seconds < -5 ? "lobby-state-right-now-question" : "lobby-state-right-now-confirmation");
            }
            else if (difference.TotalHours >= 1)
            {
                text = $"{Math.Floor(difference.TotalHours)}:{difference.Minutes:D2}:{difference.Seconds:D2}";
            }
            else
            {
                text = $"{difference.Minutes}:{difference.Seconds:D2}";
            }
        }
        StartTime.Text = Loc.GetString("lobby-state-round-start-countdown-text", ("timeLeft", text));
    }
}