// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorCloseConfirmWindow : SLWindow
{
    public CharacterEditorCloseConfirmWindow()
    {
        RobustXamlLoader.Load(this);
    }
}