// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterNameEditorWindow : DefaultWindow
{
    public CharacterNameEditorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}