// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.2

using Content.Client._Starlight.Character.UIView.Systems;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Character.UIView.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class SLCharacterView : SpriteView
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private CharacterUIViewSystem _characterViewSystem = default!;

    public bool HasView => _viewEntity != null;

    private EntityUid? _viewEntity = null;
    public SLCharacterView()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _characterViewSystem = _entityManager.System<CharacterUIViewSystem>();
    }

    public bool SetFromProfile(HumanoidCharacterProfile characterProfile)
    {
        if (_viewEntity != null)
            return _characterViewSystem.UpdateBaseView((_viewEntity.Value, null, null), characterProfile);
        _viewEntity = _characterViewSystem.CreateBaseView(characterProfile);
        return true;
    }

    public void ClearCharacter()
    {
        if (_viewEntity != null)
            _characterViewSystem.RemoveView(_viewEntity.Value);
    }

    protected override void ExitedTree()
    {
        ClearCharacter();
    }
}