// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorStepButton : ContainerButton
{
    public int EditorStep { get; set; } = -1;

    private Action<int>? _selectHandler;


    public CharacterEditorStepButton()
    {
        RobustXamlLoader.Load(this);
        OnPressed += HandlePressed;
    }

    private void HandlePressed(ButtonEventArgs obj)
    {
        if (EditorStep >= 0)
            _selectHandler?.Invoke(EditorStep);
    }

    [Access(typeof(CharacterEditorControl))]
    public void Initialize(int stepIndex, CharacterEditorStep step, Action<int> selectHandler)
    {
        if (EditorStep != -1)
            throw new InvalidOperationException($"Tried to initialize EditorStepButton:{ToString()} twice!");
        _selectHandler = selectHandler;
        EditorStep = stepIndex;
        ModeSublabel.Text = step.ModeSubText;
        ModeLabel.Text = step.ModeName;
        ModeIcon.Texture = step.ModeIcon;
    }
}