// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.UI;
using Content.Shared._Starlight.CharacterProfiles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorField : SLBox
{
    public string? LabelText { get => FieldLabel.Text; set => FieldLabel.Text = value; }

    public bool Disabled
    {
        get
        {
            return FieldControl == null || FieldControl.Disabled;
        }
        set
        {
            if (FieldControl != null)
                FieldControl.Disabled = value;
        }
    }

    public bool EnableRandomize
    {
        get => RandomizeFieldButton.Visible;
        set
        {
            RandomizeFieldButton.Visible = value;
            RandomizeFieldButton.Disabled = !value;
        }
    }

    private float _textEditWidth = float.NaN;


    public float TextEditWidth
    {
        get => _textEditWidth;
        set
        {
            if (FieldControl is LineEdit lineEdit)
                lineEdit.SetWidth = value;
            _textEditWidth = value;
        }
    }
    public ICharacterEditorField? FieldControl { get; private set; } = null;

    public bool IsInitialized => FieldControl != null;
    public CharacterEditorField()
    {
        RobustXamlLoader.Load(this);
        RandomizeFieldButton.OnPressed += HandleRandomizeField;
    }

    public void SetTextFieldValue(string newValue)
    {
        if (FieldControl is not SLLineEdit lineEdit) return;
        lineEdit.SetText(newValue, true);
        lineEdit.ForceSubmitText();
    }

    private void HandleRandomizeField(BaseButton.ButtonEventArgs args)
    {
        FieldControl?.Randomize();
    }

    private void InitializationGuard()
    {
        if (IsInitialized)
            throw new InvalidOperationException($"Tried to initialize editor field multiple times!");
    }

    public TField InitializeWithField<TField>(TField field) where TField: Control, ICharacterEditorField
    {
        InitializationGuard();
        FieldControl = field;
        return field;
    }

    public CharacterEditorDropdownEnumField<TData, TEnum> InitializeAsEnumField<TData,TEnum>(
        CharacterDataSetterDelegate<TData, TEnum> setter,
        CharacterDataGetterDelegate<TData, TEnum> getter,
        string? locPrefix = null)
        where TData: CharacterData, new()
        where TEnum : struct, Enum
    {
        InitializationGuard();
        return InitializeWithField(ICharacterEditorField.AddEnumField(this, setter, getter, locPrefix));
    }

    public CharacterEditorDropdownPrototypeField<TData, TPrototype>  InitializeAsPrototypeField<TData, TPrototype>(
        CharacterDataSetterDelegate<TData, TPrototype> setter,
        CharacterDataGetterDelegate<TData, TPrototype> getter,
        Func<TPrototype, string>? localizedNameGetter = null)
        where TData : CharacterData, new()
        where TPrototype : class, IPrototype
    {
        InitializationGuard();
        return InitializeWithField(ICharacterEditorField.AddPrototypeField(this, setter, getter,localizedNameGetter));
    }

    public CharacterEditorTextField<TData> InitializeAsTextField<TData>(
        CharacterDataSetterDelegate<TData, string> setter,
        CharacterDataGetterDelegate<TData, string> getter,
        bool allowRandomize = false)
        where TData : CharacterData, new()
    {
        InitializationGuard();
        var field = ICharacterEditorField.AddTextField(this,  setter, getter);
        if (!float.IsNaN(TextEditWidth))
            field.SetWidth = TextEditWidth;
        EnableRandomize = allowRandomize;
        return InitializeWithField(field);
    }
}