// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.UI;
using Content.Shared._Starlight.CharacterProfiles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorField : SLBox
{
    public string? Text { get => FieldLabel.Text; set => FieldLabel.Text = value; }

    public bool Disabled
    {
        get
        {
            return FieldControl == null || FieldControl.Disabled;
        }
        set
        {
            if (FieldControl != null)
                FieldControl.Disabled = value;
        }
    }

    public bool EnableRandomize
    {
        get => RandomizeFieldButton.Visible;
        set
        {
            RandomizeFieldButton.Visible = value;
            RandomizeFieldButton.Disabled = !value;
        }
    }

    private float _textEditWidth = float.NaN;


    public float TextEditWidth
    {
        get => _textEditWidth;
        set
        {
            if (FieldControl is LineEdit lineEdit)
                lineEdit.SetWidth = value;
            _textEditWidth = value;
        }
    }
    public ICharacterEditorField? FieldControl { get; private set; } = null;

    public bool IsInitialized => FieldControl != null;
    public CharacterEditorField()
    {
        RobustXamlLoader.Load(this);
        RandomizeFieldButton.OnPressed += HandleRandomizeField;
    }

    private void HandleRandomizeField(BaseButton.ButtonEventArgs args)
    {
        FieldControl?.Randomize();
    }

    private void InitializationGuard()
    {
        if (IsInitialized)
            throw new InvalidOperationException($"Tried to initialize editor field multiple times!");
    }

    public void InitializeAsEnumField<TData,TEnum>(
        CharacterDataGetterDelegate<TData, TEnum> getter,
        CharacterDataSetterDelegate<TData, TEnum> setter,
        string? locPrefix = null)
        where TData: struct, ICharacterData
        where TEnum : struct, Enum
    {
        InitializationGuard();
        FieldControl = ICharacterEditorField.AddEnumField(this, getter, setter, locPrefix);
    }

    public void InitializeAsPrototypeField<TData, TPrototype>(
        CharacterDataGetterDelegate<TData, TPrototype> getter,
        CharacterDataSetterDelegate<TData, TPrototype> setter,
        Func<TPrototype, string>? localizedNameGetter = null)
        where TData : struct, ICharacterData
        where TPrototype : class, IPrototype
    {
        InitializationGuard();
        FieldControl = ICharacterEditorField.AddPrototypeField(this, getter, setter, localizedNameGetter);
    }

    public void InitializeAsTextField<TData>(
        CharacterDataGetterDelegate<TData, string> getter,
        CharacterDataSetterDelegate<TData, string> setter,
        bool allowRandomize = false)
        where TData : struct, ICharacterData
    {
        InitializationGuard();
        var field = ICharacterEditorField.AddTextField(this, getter, setter);
        if (!float.IsNaN(TextEditWidth))
            field.SetWidth = TextEditWidth;
        FieldControl = field;
        EnableRandomize = allowRandomize;
    }

}