// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class CharacterEditorModeButton : ContainerButton
{

    private readonly CharacterEditorMode? _editorMode = null;

    public CharacterEditorMode EditorMode
    {
        get => _editorMode!;
        init
        {
            _editorMode = value;
            SetupFromMode(value);
        }
    }

    public CharacterEditorModeButton()
    {
        RobustXamlLoader.Load(this);
        OnPressed += HandlePressed;
    }

    private void HandlePressed(ButtonEventArgs obj)
    {
        EditorMode.Activate();
    }

    private void SetupFromMode(CharacterEditorMode mode)
    {
        mode.LinkButton(this);
        ModeSublabel.Text = mode.ModeSubText;
        ModeLabel.Text = mode.ModeName;
        ModeIcon.Texture = mode.ModeIcon;
    }
}