// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT
using Content.Client._Starlight.CharacterEditor.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class EditorModeButton : ContainerButton
{
    public string? ModeName { get => ModeLabel.Text; set => ModeLabel.Text = value; }

    public string? ModeSecondaryText
    {
        get => ModeSublabel.Text;
        set
        {
            ModeSublabel.Text = value;
            ModeSublabel.Visible = value != null;
        }
    }

    public Texture? Icon
    {
        get => ModeIcon.Texture;
        set
        {
            ModeIcon.Texture = value;
            ModeIcon.Visible = value != null;
        }
    }

    private Type? _editingPanelType = null;

    public Type? EditingPanelType
    {
        get => _editingPanelType;
        set
        {
            if (value == null)
            {
                _editingPanelType = value;
                return;
            }
            if (value.IsAbstract || !value.IsAssignableTo(typeof(EditorModeWidget)))
                throw new ArgumentException(
                    $"CharacterEditorMode Type:{value} must be child of" +
                    $" {typeof(EditorModeWidget)} and non-abstract");
            _editingPanelType = value;
        }
    }

    private Type? _detailsPanelType = null;

    public Type? DetailsPanelType
    {
        get => _detailsPanelType;
        set
        {
            if (value == null)
            {
                _detailsPanelType = value;
                return;
            }
            if (value.IsAbstract || !value.IsAssignableTo(typeof(EditorModeWidget)))
                throw new ArgumentException(
                    $"CharacterEditorMode Type:{value} must be child of" +
                    $" {typeof(EditorModeWidget)} and non-abstract");
            _detailsPanelType = value;
        }
    }
    public EditorModeButton()
    {
        RobustXamlLoader.Load(this);
    }
}