// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class EditorModeButton : ContainerButton
{

    private CharacterEditorMode? _editorMode = null;
    public CharacterEditorMode EditorMode { get => _editorMode!; init => _editorMode = value; }

    public EditorModeButton()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetMode(CharacterEditorMode mode)
    {
        _editorMode = mode;
        ModeLabel.Text = Loc.GetString(mode.ModeName);
        if (mode.ModeSubText != null)
            ModeSublabel.Text = Loc.GetString(mode.ModeSubText);
        ModeIcon.Texture = mode.ModeIcon;
    }
}