// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.CharacterProfiles;
using Content.Shared._Starlight.CharacterProfileSystem.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.UIEvents;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class ProfileSelectorButton : ContainerButton, IUIEventSubscriber
{
    public int Slot { get => CharacterView.Slot; set => CharacterView.Slot = value; }
    public bool IsSelected { get; private set; } = false;

    public ProfileSelectorButton()
    {
        RobustXamlLoader.Load(this);
        ToggleMode = true;
        EnabledCheck.OnToggled += OnEnabledToggle;
        OnPressed += OnSelectProfile;
    }

    private void OnSelectProfile(ButtonEventArgs args)
    {
        IsSelected = true;
        Disabled = true;
        UserInterfaceManager.RaiseGlobalUIEvent(new CharacterProfileSelectedUIEvent(Slot));
    }

    private void OnEnabledToggle(ButtonToggledEventArgs args)
    {
        if (Slot <= 0)
            return;
        if (args.Pressed)
        {
            UserInterfaceManager.RaiseGlobalUIEvent(new CharacterProfileEnabledUIEvent(Slot));
        }
        else
        {
            UserInterfaceManager.RaiseGlobalUIEvent(new CharacterProfileDisabledUIEvent(Slot));
        }

    }

    protected override void EnteredTree()
    {
        Slot = GetPositionInParent();
        UserInterfaceManager.SubscribeGlobalUIEvent<CharacterProfileUpdatedUIEvent>(this, OnCharacterSlotUpdated);
        UserInterfaceManager.SubscribeGlobalUIEvent<ActiveCharacterProfileUpdatedUIEvent>(this, OnActiveProfileChanged);
    }

    private void OnActiveProfileChanged(ActiveCharacterProfileUpdatedUIEvent ev)
    {
        if (!IsSelected)
            return;
        if (Slot == ev.Slot)
        {
            CharacterView.SetEntity(ev.Preview);
            UpdateCharacterProfile(ev.Profile);
            return;
        }
        UpdateCharacterProfile(CharacterView.LinkedProfileSlot);
        CharacterView.SetEntity(CharacterView.LinkedPreview);
        IsSelected = false;
    }

    protected override void ExitedTree()
    {
        UserInterfaceManager.UnSubscribeAllUIEvents(this);
    }

    private void OnCharacterSlotUpdated(CharacterProfileUpdatedUIEvent ev)
    {
        if (Slot != ev.CharacterProfile.Comp.Slot)
            return;
        UpdateCharacterProfile(ev.CharacterProfile);
    }

    public void UpdateCharacterProfile(Entity<CharacterProfileComponent>? profile)
    {
        if (profile == null)
        {
            CharacterName.Text = "Urist McPlaceholder";
            CharacterJob.Text = "PlaceholderJob";
            Visible = false;
            IsSelected = false;
            return;
        }
        CharacterName.Text = profile.Value.Comp.Data.Profile.Name;
        Visible = true;
        Disabled = IsSelected;
    }
}