// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using System.Numerics;
using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.CharacterProfiles;
using Content.Client._Starlight.UI;
using Content.Client.Stylesheets;
using Content.Shared._Starlight.CharacterProfiles;
using Content.Shared._Starlight.CharacterProfiles.Data;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Enumerable = System.Linq.Enumerable;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class ProfileSelectorButton : SLContainerButton
{
    public int Slot => GetPositionInParent();
    public ProfileSelectorButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        AddStyleClass(StyleClassButton);
        SetupButtonOutlines();
        OnPressed += HandleSelected;
        EnabledCheck.OnToggled += HandleEnable;
        DeleteButton.OnPressed += HandleDelete;
    }

    private void HandleEnable(ButtonToggledEventArgs obj)
    {
        RaiseUIEvent(new SetEnableCharacterProfileUIEvent(Slot, obj.Pressed));
    }

    private void HandleDelete(ButtonEventArgs obj)
    {
        RaiseUIEvent(new DeleteCharacterProfileUIEvent(Slot));
        ToggleDeleteButton(false);
        Visible = false;
    }

    private void HandleSelected(ButtonEventArgs obj)
    {
        ToggleDeleteButton(false);
        RaiseUIEvent(new SelectCharacterProfileUIEvent(Slot));
    }

    public void ToggleDeleteButton(bool visible)
    {
        DeleteButtonOutline.Visible = visible;
        DeleteButton.Disabled = !visible;
    }

    public void SetFromData(CharacterProfile? profile, Entity<SpriteComponent>? previewEntity, IPrototypeManager protoManager)
    {
        CharacterView.SetEntity(previewEntity);

        if (profile == null)
        {
            CharacterName.Text = "Urist McPlaceholder";
            CharacterJob.Text = "PlaceholderJob";
            Visible = false;
            return;
        }

        var legacyProfile = profile.GetData<LegacyCharacterData>().LegacyProfile;
        //TODO: Temp
        var favoriteJob = protoManager.Index(Enumerable.First(legacyProfile.JobPreferences));
        CharacterName.Text = legacyProfile.Name;
        CharacterJob.Text = favoriteJob.LocalizedName;
        Visible = true;
    }

    //TODO: redo this, this is skrungly
    private void SetupButtonOutlines()
    {
        if (EnabledCheckOutline.PanelOverride is  StyleBoxTexture enabledStyleBox)
        {
            enabledStyleBox.Texture = Theme.ResolveTexture("/Textures/Interface/Nano/slider_outline.svg.96dpi.png");
            enabledStyleBox.SetPatchMargin(StyleBox.Margin.All, 12);
            enabledStyleBox.SetContentMarginOverride(StyleBox.Margin.All, 0);
            enabledStyleBox.SetExpandMargin(StyleBox.Margin.All, 1);
            enabledStyleBox.TextureScale = new Vector2(1.1f);
            enabledStyleBox.Modulate = StyleNano.PanelDark;
        }
        if (DeleteButtonOutline.PanelOverride is StyleBoxTexture deleteStyleBox)
        {
            deleteStyleBox.Texture = Theme.ResolveTexture("/Textures/Interface/Nano/slider_outline.svg.96dpi.png");
            deleteStyleBox.SetPatchMargin(StyleBox.Margin.All, 12);
            deleteStyleBox.SetContentMarginOverride(StyleBox.Margin.All, 0);
            deleteStyleBox.SetExpandMargin(StyleBox.Margin.All, 1);
            deleteStyleBox.TextureScale = new Vector2(1.1f);
            deleteStyleBox.Modulate = StyleNano.PanelDark;
        }
    }
}