// SPDX-FileCopyrightText: 2025 Afterlight RnD
// SPDX-License-Identifier: ASL-1.0

using System.Numerics;
using Content.Client._Starlight.CharacterEditor.Systems;
using Content.Client._Starlight.CharacterProfiles;
using Content.Client.Stylesheets;
using Content.Shared._Starlight.CharacterProfiles;
using Content.Shared._Starlight.CharacterProfiles.Data;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.UIEvents;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Enumerable = System.Linq.Enumerable;

namespace Content.Client._Starlight.CharacterEditor.Controls;

[GenerateTypedNameReferences]
public sealed partial class ProfileSelectorButton : ContainerButton, IUIEventSubscriber
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    public int Slot { get; init; } = -1;

    private CharacterProfile? _profile = null;

    protected override void EnteredTree()
    {
        UserInterfaceManager.SubscribeUIEvent<CharacterProfileCreatedUIEvent>(this,OnProfileCreated);
        UserInterfaceManager.SubscribeUIEvent<CharacterProfileUpdatedUIEvent>(this,OnProfileUpdated);
        UserInterfaceManager.SubscribeUIEvent<CharacterProfileDeletedUIEvent>(this,OnProfileDeleted);
    }

    private void OnProfileDeleted(CharacterProfileDeletedUIEvent ev)
    {
        if (ev.Profile.Slot != Slot)
            return;
        SetFromProfile(null);
        CharacterView.SetEntity(null);
    }

    private void OnProfileCreated(CharacterProfileCreatedUIEvent ev)
    {
        if (ev.Profile.Slot != Slot)
            return;
        SetFromProfile(ev.Profile);
        CharacterView.SetEntity(ev.PreviewEntity);
    }

    private void OnProfileUpdated(CharacterProfileUpdatedUIEvent ev)
    {
        if (ev.Profile.Slot != Slot)
            return;
        SetFromProfile(ev.Profile);
    }

    protected override void ExitedTree()
    {
        UserInterfaceManager.UnSubscribeAllUIEvents(this);
    }

    public ProfileSelectorButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        AddStyleClass(StyleClassButton);
        SetupButtonOutlines();
        EnabledCheck.OnToggled += OnActivateToggled;
    }

    private void OnActivateToggled(ButtonToggledEventArgs args)
    {
        if (_profile == null)
            return;
        UserInterfaceManager.RaiseUIEvent(new CharacterProfileToggleActiveUIEvent(_profile.Slot, args.Pressed));
    }

    public void ToggleDeleteButton(bool visible)
    {
        DeleteButtonOutline.Visible = visible;
        DeleteButton.Disabled = !visible;
    }

    public void SetPreviewSprite(Entity<SpriteComponent>? previewEntity)
    {
        CharacterView.SetEntity(previewEntity);
    }

    public void SetFromProfile(CharacterProfile? profile)
    {
        if (profile == null)
        {
            CharacterName.Text = "Urist McPlaceholder";
            CharacterJob.Text = "PlaceholderJob";
            Visible = false;
            return;
        }

        var legacyProfile = profile.GetData<LegacyCharacterData>().LegacyProfile;
        //TODO: Temp
        var favoriteJob = _protoManager.Index(Enumerable.First(legacyProfile.JobPreferences));
        CharacterName.Text = legacyProfile.Name;
        CharacterJob.Text = favoriteJob.LocalizedName;
        Visible = true;
    }

    //TODO: redo this, this is skrungly
    private void SetupButtonOutlines()
    {
        if (EnabledCheckOutline.PanelOverride is  StyleBoxTexture enabledStyleBox)
        {
            enabledStyleBox.Texture = Theme.ResolveTexture("/Textures/Interface/Nano/slider_outline.svg.96dpi.png");
            enabledStyleBox.SetPatchMargin(StyleBox.Margin.All, 12);
            enabledStyleBox.SetContentMarginOverride(StyleBox.Margin.All, 0);
            enabledStyleBox.SetExpandMargin(StyleBox.Margin.All, 1);
            enabledStyleBox.TextureScale = new Vector2(1.1f);
            enabledStyleBox.Modulate = StyleNano.PanelDark;
        }
        if (DeleteButtonOutline.PanelOverride is StyleBoxTexture deleteStyleBox)
        {
            deleteStyleBox.Texture = Theme.ResolveTexture("/Textures/Interface/Nano/slider_outline.svg.96dpi.png");
            deleteStyleBox.SetPatchMargin(StyleBox.Margin.All, 12);
            deleteStyleBox.SetContentMarginOverride(StyleBox.Margin.All, 0);
            deleteStyleBox.SetExpandMargin(StyleBox.Margin.All, 1);
            deleteStyleBox.TextureScale = new Vector2(1.1f);
            deleteStyleBox.Modulate = StyleNano.PanelDark;
        }
    }
}