// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Content.Client._Starlight.CharacterEditor.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._Starlight.CharacterEditor.Widgets.Editors;

[GenerateTypedNameReferences]
public sealed partial class CharacterSlotSelector : EditorModeWidget
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    public CharacterSlotSelector()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        _cfg.OnValueChanged(CCVars.GameMaxCharacterSlots, OnValueChanged, true);
    }
    private void OnValueChanged(int newMaxCharacters)
    {
        if (ChildCount > newMaxCharacters)
        {
            for (var i = 0; i < ChildCount - newMaxCharacters; i++)
            {
                ListEntries.RemoveChild(ChildCount-1);
            }
            return;
        }

        for (var i = 0; i < newMaxCharacters - ChildCount; i++)
        {
            ListEntries.AddChild(new ProfileSelectorButton());
        }
    }
}