// SPDX-FileCopyrightText: 2025 Starlight Network
// SPDX-License-Identifier: Starlight-MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.CharacterEditor.Widgets.Editors;

[GenerateTypedNameReferences]
public sealed partial class SpeciesEditor : EditorModeWidget
{
    public SpeciesEditor()
    {
        RobustXamlLoader.Load(this);
    }
}